### ISSUE TITLE
Status of the tests?

### ISSUE THREAD

**Issue by latentflip** [waynerobinson/xeroizer#103]
Hi Wayne et al,

I am trying to contribute some more patches to xeroizer (I have a bunch in a personal fork already, as well as new support for transaction types that were launched yesterday) except I can't get the tests to run, and I don't want to be committing more code unless all the tests are actually running.

On a clean checkout of the repo master branch, and after bundle install:

```
$ bundle exec rake test:unit #=> 2 failures, 18 errors
$ bundle exec rake test       #=> 15 failures, 18 errors
```

Now I am sure some of these will be because I don't have the keys setup properly, but some are definitely code errors (mostly around passing nil/fake `parents` around it looks like.

Is this the current state of master for you as well, or is there another step I need to take?

It would be great if you could clarify in the readme the process for getting started with testing against the actual API too (what we need to do to setup a new app/what kind of app we need/where we put keys/etc).

If I can get to the point where I have passing tests I can definitely help maintain this lib as we use it in production.

Thanks!
Phil

**Comment by CloCkWeRX** [comment]
#103 #181 will help this a bit

**Comment by CloCkWeRX** [comment]
#73

**Comment by timdiggins** [comment]
@waynerobinson @CloCkWeRX wouldn't it make sense to just dump (ie. `git rm`) the acceptance tests if no one knows how to run them and hasn't for a long time? The units are all running. If we can figure out how to run some acceptance tests reasonably (not obvious given unless Xero will contribute a long-running development organization to the project) then we can always find the test in the repo.

**Comment by CloCkWeRX** [comment]
There's still a few warnings, but on master its now:
```
$ bundle exec rake test:unit
134 tests, 1206 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

We also added a travis.yml, there's a bit of account setup there to think about (it only runs unit tests).

For the acceptance tests... they still have some value.
They are run like:
```
$ KEY_FILE=~/htw-all/htw_infra/site-cookbooks/apps/files/default/xero_leave_it_test_environment.pem CONSUMER_KEY=MLQCFQY45G0TVJLMMOPIU9YLLTWYDB CONSUMER_SECRET=JKFDEVSPNCPH8MVU0NKDVN7UKPXL3T bundle exec rake test:acceptance
```
which is just doing
```
    Xeroizer::OAuthCredentials.new ENV["CONSUMER_KEY"], ENV["CONSUMER_SECRET"], ENV["KEY_FILE"]
```
I honestly would normally just chuck VCR or a fake service in instead.

**Comment by timdiggins** [comment]
@CloCkWeRX appreciate the commit to help with the README, but I'm also in favour of having VCR here. This would make getting up an running as a contributor way faster. @waynerobinson ? 

I'm sure someone might add in vcr and canned responses if we got a sense that a PR would be welcomed.

**Comment by rjaus** [comment]
I've added some details to the README regarding how to run the tests: https://github.com/waynerobinson/xeroizer#tests

If someone wants to add VCR support, create a PR.

**Comment by CloCkWeRX** [comment]
Going to close this for now, as we've done some minor improvements

**Comment by drewish** [comment]
@CloCkWeRX you'd mentioned having a travis.yml but it doesn't seem to be running the tests automatically. Worth an issue to get those turned back on?
