### ISSUE TITLE
Paths vs Strings for certificates in Xeroizer instantiation

### ISSUE THREAD

**Issue by timdiggins** [waynerobinson/xeroizer#124]
Just wondering if there is a particular reason why the initialize method for the Partner and Private Xeroizer instances take a string filepath rather than a string. Because I'm deploying to Heroku, I don't want to have to put the certificate into a git repo, but want the certificate text in a ENV var, so I'm going to try to change the initialize method (for the Private Xeroizer ) to allow me to pass a String... Would you be interested in a pull request if I do?

any suggestions how to do this?

**Comment by dominicwong617** [comment]
Sorry for the complete noob question, but what exactly does |' echo "$PRIVATEKEY"' do? I have never seen this `| echo` command before

**Comment by timdiggins** [comment]
@dominicwong617 it does seem a bit arcane. 

This is what I've worked out it does (but maybe someone else can correct, or give a reference to authority).

The pipe command is used in unix to chain the output of one function into another. But in this case it is being used to ignore the input of the other command and replace it with the output of `echo "$PRIVATE_KEY"` which is the contents of environment variable `$PRIVATE_KEY`

So in this case, assuming the system is doing something like (not really this, but something like it) `cat $OAUTH_CONSUMER_KEY | some_other_executable`, this would turn that into `cat | echo "$PRIVATE_KEY" | some_other_executable`. In fact there is no actual `some_other_executable` , but rather (I think) that ruby is reading the STDOUT, but same effect.

**Comment by daveharris** [comment]
While the above may work, it seems pretty dodgy to rely on something that underlying OS will do.

A better solution can be found in #338:
```
Xeroizer::PrivateApplication.new(key, secret, nil, private_key: ENV["XERO_PRIVATE_KEY"])
```

**Comment by mrsimo** [comment]
The solution offered in #338 would work well, but I'd recommend double checking your version of the `oauth` gem. You need at least `0.5.0` for that approach to work, and we couldn't because of another gem requiring `0.4.7`. The other suggested approach also worked for us quite well.
