### ISSUE TITLE
Payment using PUT or POST?

### ISSUE THREAD

**Issue by mech** [waynerobinson/xeroizer#179]
I was doing my usual payment when I encounter this unexpected result:

```
Couldn't find object for API Endpoint https://api.xero.com/api.xro/2.0/Payments
```

After seeing the Xero API update on Dec 1, there seems to have some Payment update on "being able to delete payment"

Deleting payment is using POST. I was wondering if Xeroizer is using PUT or POST for its payment.

It seems to me that PUT will apply payment while POST will delete payment. It is a very strange API from Xero

**Comment by maxime-d** [comment]
I'm on the current version `2.16.1` and I'm trying to update status of Payment to DELETED but the API returns again `Couldn't find object for API Endpoint` error.

**Comment by Js-per** [comment]
I am on current version xeroizer (2.16.4) trying to update the status of Payment to "DELETED". I am having the same error.

payment = XERO.Payment.find(#payment_id)

## Record successfully returns with status "AUTHORISED"

payment.status = "DELETED"
payment.save

Xeroizer::ObjectNotFound: Xeroizer::ObjectNotFound

Any help would be greatly appreciated.

**Comment by dougochris** [comment]
For anyone else who gets the ObjectNotFound response. Don't find the invoice with the id, just build one like Payment.build(id: 'ABCD-...', status: 'DELETED') and save that
