### ISSUE TITLE
Would really appreciate some more code examples for working with xeroizer

### ISSUE THREAD

**Issue by ryardley** [waynerobinson/xeroizer#187]
Hey Wayne,

Thank you so much for putting this library together! I am sure everyone in the ruby community working with xero considers it a godsend. 

One thing I have struggled with is having to go through the guts of your code and xero's object model in order to get simple things done such as create and pay an invoice.

I think it would benefit both myself and others working on ecommerce integration if, in the documentation there were a set of common simple examples of the process of how to create approve populate and pay an invoice.

Thank you again for your library!

Cheers,
Rudi

**Comment by brojsimpson** [comment]
me too :-(

**Comment by keitheous** [comment]
me three! *sad face
