### ISSUE TITLE
NoMethodError: undefined method `extract_options!' - xeroizer 2.15.6

### ISSUE THREAD

**Issue by jbhewitt** [waynerobinson/xeroizer#188]
Using ruby 2.1.4 and xeroizer version 2.15.6 I can't seem to load the gem.

Installed using bundler when I require 'xeroiser' it throws this error
```
[23] pry(main)> require 'xeroizer'
NoMethodError: undefined method `extract_options!' for [:type, {:in=>["STREET", "POBOX", "DEFAULT"]}]:Array
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/xeroizer-2.15.6/lib/xeroizer/record/validation_helper.rb:16:in `validates_with_validator'
```

**Comment by jbhewitt** [comment]
Ok using ruby 1.9.3 it works - maybe we should put a requirement for ruby 1.9.3 in the Readme file

**Comment by waynerobinson** [comment]
I've just tried this without issue. `extract_options!` comes from ActiveSupport. Could you please make sure this gem is installed with this ruby version?

**Comment by jbhewitt** [comment]
Yes ActiveSupport is installed in ruby 2.1.4 
```
bundle
Using i18n 0.6.9
Using multi_json 1.8.4
Using activesupport 3.2.16
Using atomic 1.1.14
Using builder 3.2.2
Using coderay 1.1.0
Using method_source 0.8.1
Using mini_portile 0.5.2
Using nokogiri 1.6.1
Using oauth 0.4.5
Using slop 3.4.3
Using pry 0.9.12.6
Using thread_safe 0.1.3
Using tzinfo 1.1.0
Using xeroizer 2.15.5
Using bundler 1.7.6
```

Still no go.

**Comment by waynerobinson** [comment]
Seems the way ActiveSupport works for core extensions changed in version 4.2.

I have altered the way Xeroizer requires ActiveSupport and bumped the gem version to 2.15.8 with this new method.
