### ISSUE TITLE
Creating and updating batch contacts in Xero

### ISSUE THREAD

**Issue by sri1274** [waynerobinson/xeroizer#195]
Hi,

I tried adding two contacts by providing summarizeErrors = false ,which gives the detailed response of two records even one record creation failed with some error.This looks fine.

Now I will provide two contacts for Xero,one for create and another for update the existing.In this case if any of the record got failed ,I'm receiving only the failed response but not the one that created.

It is necessary to receive the response back for every record that I provided in batch,so that I can map them to my database.

Any help will be appreciated.

**Comment by CloCkWeRX** [comment]
A reproduce script or example output would be helpful to answer this, because there's not really enough to give you a proper answer at the moment.

**Comment by CloCkWeRX** [comment]
No feedback
