### ISSUE TITLE
Making Allocations work

### ISSUE THREAD

**Issue by geoffreyd** [waynerobinson/xeroizer#196]
Has anyone managed to get assigning Allocations to CreditNotes work?

To start with I managed to get Xeroizer to send what looked like the correct XML for creating a CreditNote with Allocations, but then after talking to Xero support, they tell me that you can't inline Allocations while creating a CreditNote.

> The allocation cannot be applied at the same time the Credit Note is created by the API. This will need to happen in two separate API calls: 
> 
> Creating the Credite Note
> Applying the Allocation

So now I try and add an Allocation to an existing CreditNote (The only way I can see to do this with Xeroizer), but when saving the credit note it's POSTing to `https://api.xero.com/api.xro/2.0/CreditNotes` instead of PUTing to `https://api.xero.com/api.xro/2.0/CreditNotes/b356e488-2678-4be4-ad4b-d294df2d48d6/Allocations`, as mentioned in the docs.

This is really a very annoying API decision by Xero, as it's not very consistent with the rest of their API, so unfortunately doesn't seem to be supported by Xeroizer.

Has anyone else managed to get Allocations working? I see support was added with #83, but as above, this does not look to work.

**Comment by michaelbaudino** [comment]
Is there any update about this ? I'm having the same problem:
* when creating the credit note, then the allocation and then saving the credit note, Xero ignores the allocation (but successfully creates the credit note without any error message or exception)
* when creating the allocation on an existing credit note and then saving this credit note, Xero keeps ignoring the allocation too
* even when trying to do it from their API previewer, it keeps ignoring it! (using either PUT or POST)

I'm kind of out of options here and would love to hear about someone who managed to allocate credit notes to an invoice...

**Comment by geoffreyd** [comment]
I ended up contacting Xero help desk, and they pretty much told me that I had to make 2 calls, one to make the credit notes, then one call per credit note to set the allocations ... really not great for doing batch updates.

If you could contact them and let them know that'd you'd like this ability, it might help encourage them to fix this.

**Comment by chuckb** [comment]
When I attempt to allocate an invoice to a credit note that has available credit left, but already has another invoice allocated to it, like so:

    def self.allocate_invoice_to_credit_note(amount_to_allocate, invoice, credit_note)
        alloc = XeroApi.client.Allocation.build
        alloc.applied_amount = amount_to_allocate
        alloc.invoice = invoice.xero_invoice
        credit_note.add_allocation alloc
        # You cannot call save here, because Xero thinks you are trying to edit the credit note
        # document.  The only thing we are posting are the allocations, which is what this method does.
        credit_note.allocate
    end

You get the validation error "The invoice you are trying to allocate to has already been paid off".

My hunch is that you have to blast the allocation collection on the existing credit note prior to calling add_allocation.  Planning to try it and will comment back...

**Comment by CloCkWeRX** [comment]
Closing given #211 was merged
