### ISSUE TITLE
Payment is missing IsReconcile attribute

### ISSUE THREAD

**Issue by michaelbaudino** [waynerobinson/xeroizer#198]
[Xero Payments API doc](http://developer.xero.com/documentation/api/payments/) seems to support an `IsReconcile` parameter but the [Xeroixer Payment model](https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/payment.rb) does not seem to.

Am I missing something or would a PR be useful here ?

**Comment by waynerobinson** [comment]
PRs are always useful. :-)
