### ISSUE TITLE
Cannot Load File Error

### ISSUE THREAD

**Issue by roshinifreshdesk** [waynerobinson/xeroizer#202]
Hi

Generated the Partner App specific certificates and when i tried to Authorize using xeroizer, i am getting the following error

path_to_private_key = File.join("privatekey.pem");
path_to_ssl_client_cert = File.join("entrust-cert.pem")
path_to_ssl_client_key = File.join("entrust-private-nopass.pem")
consumer_key = "XXX"
consumer_secret = "XXX"

```
client = Xeroizer::PartnerApplication.new(
                consumer_key,
                consumer_secret, 
                path_to_private_key,
                path_to_ssl_client_cert,
                path_to_ssl_client_key
                )

request_token = client.request_token(:oauth_callback => 'http://roshini.ngrok.com')
puts "request token ---- #{request_token.inspect}"
```

.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require': cannot load such file -- active_support/time (LoadError)
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from .rvm/gems/ruby-1.9.3-p484/gems/xeroizer-2.15.8/lib/xeroizer/record/xml_helper.rb:1:in `<top (required)>'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from .rvm/gems/ruby-1.9.3-p484/gems/xeroizer-2.15.8/lib/xeroizer/record/base.rb:4:in`<top (required)>'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from .rvm/gems/ruby-1.9.3-p484/gems/xeroizer-2.15.8/lib/xeroizer.rb:24:in `<top (required)>'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`require'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from .rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in`require'

Let me know, if am missing out something

Thanks
Roshini

**Comment by CloCkWeRX** [comment]
You'll want to make sure you have the right version of activesupport available - its not clear if the wrong version is included from your application's Gemfile.lock or from the gemspec of xeroizer.
