### ISSUE TITLE
Consider swapping to an organisation and giving more contributors commit access

### ISSUE THREAD

**Issue by CloCkWeRX** [waynerobinson/xeroizer#207]
There's a lot of open pull requests at the moment, most of them pretty simple or straight forward.  The payroll branch is working enough to use in production, but is missing a lot of little useful fixes from master.

People are forking and fixing, but it would be better to find some of the heavier users/committers and consider granting commit access. This works really well for organizations like PEAR or rabbitvcs - when we run out of time, if you are more interested than us, we'll probably extend you access.

Consider the same here. Looking at the network graph (https://github.com/waynerobinson/xeroizer/network) plus other bits and pieces , @ghiculescu  and @ben-biddington would make sense to grant access to.

**Comment by waynerobinson** [comment]
I'm not quite ready to make this leap yet. I will commit to being a little more on top of PRs though (I've been sick the last week).

**Comment by rjaus** [comment]
@CloCkWeRX what are the benefits of an organisation in this case?

@ghiculescu if you want to put together a PR for your payroll fork / branch, keen to get you more involved.

**Comment by CloCkWeRX** [comment]
I think we achieved the spirit of this - there's a few more contributors, and we're OK to add more as people go into hibernation
