### ISSUE TITLE
Spaces in strings are being replaced by plus signs

### ISSUE THREAD

**Issue by rkjbnz** [waynerobinson/xeroizer#216]
This seems to just have happened recently. When creating an invoice all the spaces in the strings are being replaced with plus signs.

Code im using:

`invoice.build_contact(:name => "#{contact.try(:name)}", :email_address => "#{@job.contact.try(:email)}")`

Also tried it

`invoice.build_contact(:name => contact.try(:name), :email_address => contact.try(:email))` 

and without the try

`invoice.build_contact(:name => contact.name, :email_address => contact.email)`

and this is how its going into Xero. Also happening on the line item description.

![screen shot 2015-04-30 at 11 39 46 am](https://cloud.githubusercontent.com/assets/1802057/7403858/aea04486-ef2e-11e4-9858-46e564e0bfaf.png)

The information is appearing correctly in my system seems to be an issue when sending into Xero, perhaps an escaping problem?

**Comment by CloCkWeRX** [comment]
Going to suggest that's xero's side and likely since resolved.
