### ISSUE TITLE
Seems Employee is mapping only 4 attributes

### ISSUE THREAD

**Issue by fertobar** [waynerobinson/xeroizer#221]
Hi @waynerobinson !
I notice the Employer mapping is returning now only 4 basic attributes (id, first name, last name and status) in comparison with http://developer.xero.com/documentation/payroll-api-us/employees/ that have many others. 
I tried the payroll branch and works in a similar way.
There is a way for get all mapping via Xeroizer, or the map for all Employees attributes is a pending feature? 
In case you need help with the Payroll feature, just let me know.
thanks!

**Comment by fertobar** [comment]
thanks @CloCkWeRX !
after that merge I could use e.g. xero.Employee.all ? Because I'm using your branch, and I see the new attributes in the model, but I'm only getting the defaults 4 in the response.
I'm missing something, may be in the Xero Admin?
thanks

**Comment by rjaus** [comment]
All Employee attributes should now be supported: https://github.com/waynerobinson/xeroizer/blob/payroll/lib/xeroizer/models/payroll/employee.rb
