### ISSUE TITLE
Is possible to edit/remove line items on Authorised Invoice?

### ISSUE THREAD

**Issue by dan1d** [waynerobinson/xeroizer#238]
I couldn't find out how to remove/edit line items from an invoice without the line item ID, as the line item response from xero doesn't have an ID.  Do you know if this is possible?. 
Or I just have to remove the invoice and push it again with the new line items?
Is there a better way?

**Comment by vkbrihma** [comment]
Did you find any solution? Thanks!

**Comment by oowowaee** [comment]
The Xero Api documentation says the following:
```LineItemID | The Xero generated identifier for a LineItem. It is recommended that you include LineItemIDs on update requests. If LineItemIDs are not included with line items in an update request then the line items are deleted and recreated.```

However, when pushing a new line item without a line item ID I am seeing it being added, and not replacing existing items in Xero.

**Comment by conraddecker** [comment]
@oowowaee Does the latter snippet of code that you included actually work? It doesn't seem to work for me at the moment. 

@waynerobinson is it possible to delete line items from an invoice by chance?

**Comment by jvnill** [comment]
@conraddecker the code of @oowowaee works for me. eg given an invoice that currently has multiple line items, the following code snippet will delete all line items leaving the invoice with just 1 line item.

```
    xero_invoice.line_items = []

    xero_invoice.add_line_item(
      description: 'Valuation Fee',
      quantity: 1,
      unit_amount: 123,
      account_code: '4111'
    )

    xero_invoice.save
```

**Comment by conraddecker** [comment]
@jvnill Thanks a bunch for taking the time to respond. I haven't looked at this in a bit, think I went with a workaround for the time being. I'll be sure to hop back in and give it another shot and report back. 

Cheers

**Comment by jvnill** [comment]
@conraddecker I forgot to update it here but my code above doesn't work.  Found out that you need to load the line items first by calling `xero_invoice.line_items` and then set that to an empty array to clear it.

```
    xero_invoice.line_items # need to load line items first before clearing it
    xero_invoice.line_items = []

    xero_invoice.add_line_item(
      description: 'Valuation Fee',
      quantity: 1,
      unit_amount: 123,
      account_code: '4111'
    )

    xero_invoice.save
```
