### ISSUE TITLE
Is logging intentionally broken for model?

### ISSUE THREAD

**Issue by yyyc514** [waynerobinson/xeroizer#240]
I see this in the readme:

```
client = Xeroizer::PublicApplication.new(YOUR_OAUTH_CONSUMER_KEY,
                                         YOUR_OAUTH_CONSUMER_SECRET,
                                         :logger => XeroLogger)
```

But yet Xeroizer::Record::Base includes this:

```
        def log(what)
          Xeroizer::Logging::Log.info what
        end
```

And by default `Xeroizer::Logging::Log` points to `Log = DevNullLog`... am i just supposed to hack this constant to point it to a logger of my choosing?  Seems weird to pass in `:logger` and then have it ignored for request logging.

Am I missing something?

**Comment by house9** [comment]
I know this is an old post, but the following should work:

- `logger: Logger.new(STDOUT)` OR
- `logger: Rails.logger`
