### ISSUE TITLE
How to access to EmployeeAU

### ISSUE THREAD

**Issue by nqtien310** [waynerobinson/xeroizer#243]
in employee.rb , I can see that we have definition for EmployeeAU but somehow it was commented out , do we have anyway to access to that EmployeeAU model or add a new field (:ordinary_earnings_rate_id for example) to Employee model ?

  #   class EmployeeAU < Employee
  #     string :occupation
  #     string :classification # length: 100
  #     string :ordinary_earnings_rate_id
  #     boolean :is_authorised_to_approve_leave

  #     string :title # (max length = 10)
  #     string :twitter_user_name # (max length = 50)
  #     # PayrollCalendarID Xero unique identifier for payroll calendar for the employee
  #     # BankAccounts  See BankAccount
  #     # SuperMemberships  See SuperMemberships
  #   end

**Comment by CloCkWeRX** [comment]
You are probably best off re-opening the Employee class and adding in the various other bits and pieces you need for now - to support the different APIs for US, AU, etc with the same model names is probably going to need a rewrite of big chunks of the API for the library to support it.

http://www.runtime-era.com/2012/12/reopen-and-modify-ruby-classes-monkey.html

**Comment by rjaus** [comment]
Try the Payroll Branch: https://github.com/waynerobinson/xeroizer/blob/payroll/lib/xeroizer/models/payroll/employee.rb
