### ISSUE TITLE
How to retrieve detail data of Employee

### ISSUE THREAD

**Issue by nqtien310** [waynerobinson/xeroizer#245]
My scenario to fetch detail data of a 1 employee ( specific by ID )

```
result = gateway.Employee.find(xero_employee_id)
```

However, the "result" only contains the fields defined within models/employee.rb, which is "first_name", "last_name". But when I use Xero API previewer, that API endpoint returns much more detail data for that employee ( "DateofBirth, "OpeningBalances" , "SuperMemberships" etc.. )

The question Is there anyway I can include those data in the "result" returned by Xeroizer ? ( some of them are nesting ) , what i wanna achieve is:

```
result.opening_balances.first.opening_balance_date
```

PLease note that i'm using API for Australia

**Comment by rjaus** [comment]
This should be resolved by using the Payroll branch.  https://github.com/waynerobinson/xeroizer/blob/payroll/lib/xeroizer/models/payroll/employee.rb
