### ISSUE TITLE
Exceptions' `to_s` should return message

### ISSUE THREAD

**Issue by jamierumbelow** [waynerobinson/xeroizer#253]
Currently, the e.g. `ApiException` classes don't return a useful message when `to_s` is called. This makes debugging in the IRB a pain, since all calls need to be wrapped in `begin` blocks.

Is there a particular reason why this is the case? Does anybody have an objection to me changing this and submitting a PR?

**Comment by CloCkWeRX** [comment]
Fire a PR in at will!

**Comment by jamierumbelow** [comment]
(Sorry!)

**Comment by CloCkWeRX** [comment]
All good, I'm just going through and doing a bit of cleanup
