### ISSUE TITLE
Filenames with spaces can't be attached

### ISSUE THREAD

**Issue by nnc** [waynerobinson/xeroizer#256]
Trying to attach a file with spaces in filename will result in 404 error being returned by Xero.

I solved this problem with replacing `CGI.escape` with `URI.escape` and everything is working fine for us for a couple months now.
However, `URI.escape` is _obsolete_ since Ruby 1.9.2, but is still present in 2.2.3, so I'm not sure what obsolete means and if it will actually be removed any time soon. Still need to look into that and maybe replace it with something more appropriate and/or future proof.

**Comment by cameronbourgeois** [comment]
Hi @nnc I had a related issue where filenames containing brackets where causing an error:  `Xeroizer::OAuth::UnknownError (signature_invalid:Failed to validate signature)`

My quick fix was just to use the Rails String method `.parameterize` to make my filenames uniform.
