### ISSUE TITLE
ssl key file in version control?

### ISSUE THREAD

**Issue by TJM** [waynerobinson/xeroizer#259]
We have a general policy that SSL Key's should not be in version control, especially github. It appears to me (an IT guy, not a ruby developer) that this module requires the SSL Key to be in a file, rather than a "string" (a really long string) which could be set in the environment or in Rails.application.secrets? Am I wrong? Is there some way to provide the SSL Key (at a minimum) and/or Cert without a "path/to/file.pem" ?

We have a workaround in our case because we can make a symlink to ../shared/config/xero-key.pem, but what if we were deploying to a container provider like heroku? or something similar (ECS?)

**Comment by lpil** [comment]
:+1:

**Comment by house9** [comment]
:+1:

**Comment by lpil** [comment]
Oh man, that's not nice.

**Comment by CloCkWeRX** [comment]
I'd recommend solving this with your deployment tools (ie; chef, capistrano, similar); rather than in the gem.
