### ISSUE TITLE
Xeroizer::OAuth::UnknownError: nonce_used

### ISSUE THREAD

**Issue by ptrikutam** [waynerobinson/xeroizer#260]
I'm currently using the Xeroizer gem to retrieve a set of invoices. For some reason, I'm getting the following error: 

```
Xeroizer::OAuth::UnknownError: nonce_used:The nonce value "y6e1pJtSMRLOswlnlXMjy0kLEJni9CKhXoE9KQI" has already been used
	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/xeroizer-da7bed43132f/lib/xeroizer/http.rb:160:in `handle_oauth_error!'
	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/xeroizer-da7bed43132f/lib/xeroizer/http.rb:116:in `http_request'
	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/xeroizer-da7bed43132f/lib/xeroizer/http.rb:31:in `http_get'
	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/xeroizer-da7bed43132f/lib/xeroizer/application_http_proxy.rb:16:in `http_get'
	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/xeroizer-da7bed43132f/lib/xeroizer/record/base_model.rb:120:in `all'
	from (irb):3
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```
The code I'm trying to execute is `Xero.app.Invoice.all` in my console. In actual use in production we execute it with a `where` clause limiting the invoice ID.

According to the [Xero OAuth Issues page](http://developer.xero.com/documentation/getting-started/oauth-issues/):

> It may be that the your application is resubmitting the same OAuth request a second time (a double hit) somehow.

Is anyone else having this problem? How would I go about debugging this?

**Comment by CloCkWeRX** [comment]
I do see it sporadically in production with batch calls;  but it's a pain
to track down/reproduce.
I strongly suspect its the xero api at fault tbh, as it occurs even with
explicitly refreshing credentials between calls - and the nonce gets
calculated should be avoiding collisions fairly well afaik.

**Comment by ptrikutam** [comment]
Interesting, thanks for the info @CloCkWeRX. Did you find any temporary workarounds?

**Comment by ptrikutam** [comment]
Bumping to see if anyone else has encountered this issue...

**Comment by ptrikutam** [comment]
Alright -- I've been digging on this and have been working with Xero support to try and get to the bottom of this. Unfortunately no real progress has been made, and this continues to be an issue with the latest version of the xeroizer gem.

I have noticed we get this error whenever we try to do any kind of batch call. We even have one where we set the where clause to check for one of two specified invoice IDs, and that CONSISTENTLY had issues. The where clause would look something like this:

```ruby
client.Invoice.all(where: "InvoiceNumber==\"INV1X\" OR InvoiceNumber==\"INV2X\"")
```

As soon as that clause was set to only retrieve one at a time, the request goes through without issue:

```ruby
client.Invoice.all(where: "InvoiceNumber==\"INV1X\"")
```

The only thing that I've found that worked so far to stop getting this error was reverting the version of Xero way back (I had to go as far back as 3faea682). This was originally what was being used in our codebase before we started seeing this issue.

You can see the comparison of what's changed here: https://github.com/waynerobinson/xeroizer/compare/3faea6829fbc54deac5737535e2de3e50b5ce8b4...master

I'm going to try and dig through that and see if I can find the source of the issue, but for the time being we've reverted back to the old one. I'll report back if I'm able to discover anything useful.

Hopefully this at least gives someone else a clue as to what's going on, and hopefully someone else is able to shed light on the error!

**Comment by CloCkWeRX** [comment]
Ah nice. Can you effectively git bisect it?

**Comment by ptrikutam** [comment]
I'll try to do that a bit later this week.


--
415.326.3397
pavan@graybike.co
graybike.co

**Comment by ptrikutam** [comment]
Aaaand just as I sit down to try and bisect this, it works fine. On all revisions. I have no idea how to reproduce.

**Comment by ptrikutam** [comment]
If I can find a way to consistently reproduce this, I'll reopen it, but until then ¯\_(ツ)_/¯

**Comment by CloCkWeRX** [comment]
https://community.xero.com/developer/discussion/3143315

**Comment by CloCkWeRX** [comment]
```
module OAuth::Client
  class Helper
    include OAuth::Helper

    # ... this is maybe the only thing that looks like it could cause doubled nonce
    # if the OAuth::Client isn't re-instantiated on bulk calls.
    def nonce
      options[:nonce] ||= generate_key
    end
```

**Comment by waynerobinson** [comment]
Yes, that definitely looks like it could be a problem.

**Comment by waynerobinson** [comment]
But is that in the OAuth library though? Not Xeroizer?

**Comment by ptrikutam** [comment]
For what it's worth, I was unable to set the User-Agent header as well via xeroizer. I kept getting "OAuth Client Library" or something along those terms (not on my dev machine right now, can't look up the specifics). Not sure if that's helpful but I figured I'd log it here.

**Comment by scantem** [comment]
I've been experiencing this problem too with large batches but haven't been able to pinpoint where it falls over yet.

**Comment by Js-per** [comment]
I also have this issue with batch calls on invoices. Although when I switch to demo app, I have no issue.

**Comment by SorchaAbel** [comment]
I too have had this issue with batch calls on invoices

**Comment by waynerobinson** [comment]
The only thing I can possibly think of is the nonce generator used doesn't
use enough entropy.

**Comment by robzolkos** [comment]
I applied this [change](https://github.com/Copirite/oauth-ruby/commit/857d170073fc706363192a9d65bc2bf68ba439ba) to a fork of `oauth` gem and didn't get this error (after getting it consistently every single time I used a batch operation).

I'm not sure what adverse affects this will have but this solved the issue for us.

**Comment by CloCkWeRX** [comment]
We *should* be instantiating a new OAuth::Client::Helper or similar each time; but @robzolkos did you want to try sticking in a logger there?

IE:
```
  def nonce
     logger = Logger.new(STDOUT)
     logger.debug("I'm being lazy and not making a new nonce!\n#{self.inspect}") if options[:nonce]

     options[:nonce] ||= generate_key
  end
```

That might really help us understand if we've missed something obvious and you can consistently reproduce this.

For consistency; you probably also want to change your fork to be

```
     options[:nonce] = generate_key
```

so that options[:nonce] is never out of sync

**Comment by robzolkos** [comment]
@CloCkWeRX seems my situation was a false positive.  This morning started getting the nonce error again.  It wasn't until the 3rd run that it worked.  So it doesn't seem that this issue is related to this line in the oauth code after all.

**Comment by mhssmnn** [comment]
@CloCkWeRX I think you're right that this is on Xero's side. I've been logging all our requests to Xero, then checking for duplicate nonces. And after getting a `nonce_used` error this morning, I found no duplicates.

**Comment by toxaq** [comment]
I've just seen a bunch of these inline with a bunch of net timeout exceptions. Is there different handling at Xero for the nonce auth vs the actual request? This error may happen when part of the process goes wrong... Either way, it doesn't seem to be a Xeroizer issue. 

In saying that, I never saw this error before having to upgrade the gem. I'd locked to an earlier Xeroizer version because of the OAuth locked library issue. I tried a diff at the time of upgrade and couldn't see anything.
