### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by softdevbeing** [waynerobinson/xeroizer#267]
Hi,
I am using xeroizer gem to fetch data.
But I have an issue while authorizing xero public app.
I used your sample app structure.

        def new
            request_token = @xero_client.request_token(:oauth_callback => 'http://yourapp.com/xero_session/create')
            session[:request_token] = request_token.token
            session[:request_secret] = request_token.secret

            redirect_to request_token.authorize_url
        end

        def callback
            @xero_client.authorize_from_request(
                    session[:request_token], 
                    session[:request_secret], 
                    :oauth_verifier => params[:oauth_verifier] )

            session[:xero_auth] = {
                    :access_token => @xero_client.access_token.token,
                    :access_key => @xero_client.access_token.secret }

            session[:request_token] = nil
            session[:request_secret] = nil
        end

But I always get session[:request_token] as nil.
So my question is 
  session[:request_token] is kept after redirecting?
Above code is correct way?
Thanks.

**Comment by cameronbourgeois** [comment]
You're code looks perfect @softdevbeing - You must have some unrelated session issues in your app. Check that your session store is actually recording your sessions i.e. check your cookie is being set if using cookiestore, or check database if using activerecord

**Comment by softdevbeing** [comment]
Thanks for your helping @cameronbourgeois 

I fixed.

**Comment by Simratpreet** [comment]
I am integrating xeroizer gem for XERO API in Rails App. When I am trying to retrieve contacts like "client.Contact.all", I am getting error "undefined method info for false:False class".
