### ISSUE TITLE
EarningsLine

### ISSUE THREAD

**Issue by colleenbprice** [waynerobinson/xeroizer#268]
I forked so that I could add paystub to the payroll branch, but I have run into a dilemma.  EarningsLines  on the Payroll-US API have a EarningsTypeID instead of an EarningsRateID like the Payroll-AU EarningsLines.  To me that means I should create a new EarningsLine class and perhaps call it EarningsLineUS.  Or should I create two separate Payroll Modules, one named PayrollAU and the other PayrollUS and recreate all of the models with their differing attributes in each?  I haven't looked into it closely, but I am going to make a guess that it is not just EarningsLine that is different between the two APIs.

**Comment by artspool-nyc** [comment]
We have a US Payroll branch on our fork which we developed partially at Pivotal Labs and are currently using in production with our pilot clients. Feel free to look around in there to see if you see any useful patterns.
https://github.com/artspool-nyc/xeroizer/tree/payroll-spike

Note: this branch is quite a lot commits behind the master Xeroizer repository.

**Comment by colleenbprice** [comment]
I went ahead and just added the different fields to the class and it works.  See PR for details: https://github.com/waynerobinson/xeroizer/pull/269
