### ISSUE TITLE
Logging http activity

### ISSUE THREAD

**Issue by brancusi** [waynerobinson/xeroizer#270]
Hi,

1. I'm using a private app, wondering if there is a way to access the generate xml or json from a `client.Invoice.batch_save` call as well as the raw response? 

2. How can I log the http activity for the app in general? I see some references to `http_debug_output` but not sure how to hook this up.

Any tips would be much appreciated.

Thanks

**Comment by nnc** [comment]
@brancusi try [http_logger](https://github.com/railsware/http_logger) gem instead of fiddling with `http_debug_output`. We've been using it for a while, and with great success.

We just had to turn on header logging and increase the limit to 1MB, like this:
```ruby
HttpLogger.log_headers = true
HttpLogger.collapse_body_limit = 1_232_896 # Log up to 1 MB of req/resp body
```

**Comment by brancusi** [comment]
Thank you
