### ISSUE TITLE
Access all attributes for a Xero record

### ISSUE THREAD

**Issue by bauschri** [waynerobinson/xeroizer#273]
Hey!

i try to access the _Name_ field on a Xero Inventory Item, i need to Monkey-Patch the Item class?

do i really need to do that?

thanks for the help

``` ruby
class Xeroizer::Record::Item
  string :name, :api_name => 'Name'
end
```

**Comment by rjaus** [comment]
Hey @bauschri 

I suggest upgrading to the latest version: https://github.com/waynerobinson/xeroizer/releases/tag/v2.17.0

This now works as expected:
```
item = xero.Item.first

item.name

item.name = 'new name'

item.save
```
