### ISSUE TITLE
no tags in repo since 2.15.8

### ISSUE THREAD

**Issue by jrochkind** [waynerobinson/xeroizer#279]
The last version tag in the git repo is `v2.15.8.  But we're up to 2.16.1, but it doesn't look like you've been tagging the repo since then?

Would it be possible to start again? Tags in the repo makes it easier (possible?) to figure out what version of the code corresponds to what gem, when debugging or considering changes. 

If you use the bundler `rake gem release` task to release, it tags for you; maybe you stopped using that task after 2.15.8?

**Comment by CloCkWeRX** [comment]
I plan to do this/update the github releases shortly.

**Comment by CloCkWeRX** [comment]
Fixed
