### ISSUE TITLE
Version bump needed?

### ISSUE THREAD

**Issue by customersure** [waynerobinson/xeroizer#282]
Hey,

Forgive us if we’ve misunderstood or misread, but it looks as if Xeroizer needs a version bump to continue working for most people after Xero’s SHA2 SSL upgrade in April?

The new certificate has been added to the gem (https://github.com/waynerobinson/xeroizer/commit/ad412515c1d68e567d77c88fa128671335547ac2), but no new version has been released since then, meaning that anyone who is tracking RubyGems and not Github will suffer broken apps when the certificates are upgraded.

Would it be possible to release a bumped version of the gem, so we can track a known stable version rather than git HEAD or our own fork?

Apologies if we’ve missed something – tried to double check that we’re correct about this, but it’s tricky to corroborate everything, especially with the repo not being tagged (https://github.com/waynerobinson/xeroizer/commit/ad412515c1d68e567d77c88fa128671335547ac2) 

Thanks!

**Comment by Rio517** [comment]
It also needs a version bump to work with rails 5.  For now, one must pull straight from github.

```ruby
gem 'xeroizer', git: 'https://github.com/waynerobinson/xeroizer.git', ref: '29527969f2c18593ce4b36a192182c8bebe15fee'
```

The bug recently fixed is also generally tough to diagnose.  Users will be wondering why their rails 5 upgrade is running ridiculously slow and why so many codepaths with big decimals fail.  Eventually, they'll figure out it is this gem slowing them down.  

Please version bump when you guys have a chance!

**Comment by SylarRuby** [comment]
@waynerobinson Who else apart from you that could do these changes?

**Comment by CloCkWeRX** [comment]
We'll prep a release soon
