### ISSUE TITLE
Thoughts on purchase orders

### ISSUE THREAD

**Issue by brancusi** [waynerobinson/xeroizer#284]
Hi,

Wondering what your thoughts are on adding purchase order support. Is this something others have requested?

Thank you

**Comment by waynerobinson** [comment]
Ultimately, Xerozier's goal is to support the entire API from Xero. However, I personally haven't had a huge amount of time to work on this library of late. I'm always happy to accept PR's and I plan on getting better at doing so quicker.

**Comment by geekdeepak** [comment]
@waynerobinson created a PR to add purchase orders .

**Comment by CloCkWeRX** [comment]
#288
