### ISSUE TITLE
Batch Save chunk size

### ISSUE THREAD

**Issue by abousamra** [waynerobinson/xeroizer#286]
Xero API documentation recommends batch size to be 50 because they have a maximum of 3.5 MB per request. The default value at the code here is 2000. Any recommendations around that?

**Comment by waynerobinson** [comment]
2,000 has worked for us because our requests are quite small, but I will change the default.

In the meantime, you can pass in your own chunk size into batch_save.

**Comment by abousamra** [comment]
Yeah I see. Thanks for your reply.
