### ISSUE TITLE
Date and DueDate not being set on Invoice

### ISSUE THREAD

**Issue by fractalcactus** [waynerobinson/xeroizer#290]
Hi there,

I've been successfully creating invoices with the minimum parameters:
`invoice = @xero_connection.Invoice.build(type: 'ACCPAY', contact: get_xero_contact_object(contact_id))` + adding line items

However, now when I try to create an invoice with more parameters, I get  `Xeroizer::ApiException: ValidationException:`
`The Date field must be specified.` and `The document DueDate field must be specified.`
The XML returned with the  `Xeroizer::ApiException: ValidationException:` doesn't have `<Date>` or `<DueDate>` fields in it

This is perplexing, because I do create the invoice with the `Date` and `DueDate` parameters:
`invoice = @xero_connection.Invoice.build(type: 'ACCREC', status: 'AUTHORISED', reference: Date.today.strftime("%B"), date: '2016-04-01', due_date: '2016-04-14', contact: get_xero_contact_object(contact_id))`

When I inspect the `invoice` object before saving, `invoice.valid?` returns `true` , and running `invoice.line_items.each{|li| puts li.valid?}` returns `true` for each line item. Also, I get the correct date returned when I call `invoice.date` and `invoice.due_date` The dates are definitely in the right format, as I copied the YY-MM-DD format from the xeroizer docs example, `trial_balance = xero.TrialBalance.get(:date => '2011-03-21')`

Using Xeroizer has been fantastic, and the documentation is great. Thanks for any help!

**Comment by fractalcactus** [comment]
<img width="755" alt="screen shot 2016-04-20 at 12 38 11 pm" src="https://cloud.githubusercontent.com/assets/8527715/14659997/d7800a9c-06f4-11e6-8af2-c7697fef7e70.png">

**Comment by waynerobinson** [comment]
I would recommend trying real `DateTime` or `Time` objects, rather than strings.

**Comment by fractalcactus** [comment]
Thanks @waynerobinson that solved it!
<img width="755" alt="screen shot 2016-04-20 at 12 38 11 pm" src="https://cloud.githubusercontent.com/assets/8527715/14660094/0a30b0d0-06f6-11e6-87b7-381a6daa0e61.png">
Just opened a PR to change the README.md so the date example creates a DateTime object
