### ISSUE TITLE
Is there a way we can override the default Net::HTTP read_timeout?

### ISSUE THREAD

**Issue by ccelestial** [waynerobinson/xeroizer#296]
When posting asynchronously (Sidekiq workers) respond from xero took longer than the read_timeout of the http_post. Is there a way we could configure it in our code? We want to change it from 30 to maybe 60-90 seconds.

**Comment by CharlesHarley** [comment]
The initialisers for PublicApplication, PrivateApplication and PartnerApplication all have an options hash parameter that accepts a timeout element for overriding the read_timeout. e.g.:

`client = Xeroizer::PublicApplication.new(YOUR_OAUTH_CONSUMER_KEY, YOUR_OAUTH_CONSUMER_SECRET, {timeout: 120})`

**Comment by CloCkWeRX** [comment]
Nice work @CharlesHarley
