### ISSUE TITLE
Line Item Validation on Invoice Create

### ISSUE THREAD

**Issue by Js-per** [waynerobinson/xeroizer#297]
Looking to add some validation for Line Item - Description. See below, Xero Web App invalidates invoices without Line Item - Description.

Happy to make a pull request and update.

Look forward to hearing back.

![screen shot 2016-06-24 at 12 16 10 pm](https://cloud.githubusercontent.com/assets/3760126/16325999/5f863904-3a06-11e6-9dc3-673413f89e0b.png)

**Comment by rjaus** [comment]
Correct, Description is a required field for lineitems.

Added a commit here: https://github.com/rjaus/xeroizer/commit/5d0c7a03eaf592c8985e8490e781770a2cd72220

**Comment by CloCkWeRX** [comment]
Want to beam that in as a PR?
