### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Simratpreet** [waynerobinson/xeroizer#306]
I am integrating xeroizer gem for XERO API in Rails App. When I am trying to retrieve contacts like "client.Contact.all", I am getting error "undefined method infoo for false:False class".

**Comment by cameronbourgeois** [comment]
Is that the exact error? `infoo` sounds like a typo.

**Comment by Simratpreet** [comment]
It is info

**Comment by CloCkWeRX** [comment]
Unfortunately without a bit more of a reproduce script; not much we can do. 

```
clockwerx@clockwerx-laptop:~/xeroizer$ ack-grep "infoo" | wc -l
0
```
