### ISSUE TITLE
Online Invoice Url

### ISSUE THREAD

**Issue by SylarRuby** [waynerobinson/xeroizer#310]
When will we'll see [this feature](https://developer.xero.com/documentation/api/invoices/#onlineinvoice)?

**Comment by SylarRuby** [comment]
Anyone? How to extract the invoice url from this? I struggle to figure this or to even make my own method for the gem

```
def pdf(id, filename = nil)
   pdf_data = @application.http_get(@application.client, "#{url}/#{CGI.escape(id)}", :response => :pdf)
   if filename
     File.open(filename, "wb") { | fp | fp.write pdf_data }
     nil
   else
     pdf_data
   end
end
```

**Comment by CloCkWeRX** [comment]
```Individual Invoices and Credit Notes can also be returned in PDF format by setting the “Accept” value in the http header to “application/pdf”.```
https://developer.xero.com/documentation/getting-started/http-requests-and-responses/

**Comment by waynerobinson** [comment]
I'm not really sure what you're trying to achieve. The `#pdf` method is used to download the PDF version of the invoice, either directly to a file (passed in filename) or returned as a blob. 

I don't believe there is a way to direct-link to the PDF version within Xero. It requires authentication and that `Accept` header in the request as @CloCkWeRX mentioned.

**Comment by waynerobinson** [comment]
Sorry, if you want to get that online invoice URL, you'll have to request it separately as Xero didn't see fit to just include it as part of the standard Invoice detail response.

The _standard_ way to do this would be via another model, given that it's an entirely new endpoint. But that feels pretty heavy. Otherwise, you could write a method to get it similar to the way the PDF method works above. E.g.

`@application.http_get(@application.client, "#{url}/#{CGI.escape(id)}/OnlineInvoice")`

However, you'll have to parse that XML response manually.

**Comment by SylarRuby** [comment]
I dont mind making extra calls because all I need is the url and then id save it on the users table.

**Comment by SylarRuby** [comment]
@waynerobinson   Now that I have the url, I think to be able to get it everyone would find it useful. A PR? The url is saved to a table column so  all I need to do is like to it.

**Comment by stellard** [comment]
Hi Sylar, I would find this feature really useful too. Are you using a branch that I can look at?

**Comment by rjaus** [comment]
@stellard @SylarRuby I've added the OnlineInvoice feature to the gem, let me know what you think. #413 

I've implemented it as a separate model, which is a little overkill, but more in line with how the API is structured.

If that's not inline with your implementation, you could add a helper method to the Invoice model to return the online_invoice_url directly.

**Comment by rjaus** [comment]
Re-open this issue if you'd like to discuss further.
