### ISSUE TITLE
Unknown error - xero api may be down

### ISSUE THREAD

**Issue by james-purr** [waynerobinson/xeroizer#318]
I have sporadically been getting the error message:

`Completed 500 Internal Server Error in 8193ms (ActiveRecord: 1.0ms)`
`Xeroizer::OAuth::UnknownError (Xero API may be down or the way OAuth errors are provided by Xero may have changed.):`

error occurs on a line where I'm simply trying to gather all invoices from the client - pretty standard code:

`@xero_client = session[:xero_client]`
error occurs on this line:
`@all_invoices = @xero_client.Invoice.all.map {|invoice| invoice.to_h}`

this is pretty standard stuff from the docs but for what its worth - this is how the token is generated:

```
    session[:request_token] = @request_token.token
        session[:request_secret] = @request_token.secret
        session[:xero_client] = Rails.application.config.xero_client

        session[:xero_client].authorize_from_request(
        session[:request_token], 
        session[:request_secret], 
        :oauth_verifier => params[:oauth_verifier] )

        session[:xero_auth] = {
        :access_token => session[:xero_client].access_token.token,
        :access_key => session[:xero_client].access_token.secret }
```

I've never come across this before until the last few weeks when our client has been beta testing our app - is it likely that this was just the api being down? I've dug around and can't find any other explanation.

**Comment by james-purr** [comment]
log times for the error:

2016-08-23T10:45:18.290664

2016-08-23T10:47:59.871513

2016-08-23T10:53:05.987444

**Comment by waynerobinson** [comment]
I would imagine any 5xx error returned after 8+ seconds is related to the
API itself.

**Comment by nnc** [comment]
Xero has had some issues with the API last 2-3 days where some requests would fail with HTTP 503 being returned, and others would be OK.
According to their [status site](https://status.developer.xero.com) this was resolved on August 31, but we've still seen a few of those after that, so...

Their recommended workaround is to retry requests that fail with 503 Service Unavailable, but Xeroizer does not have this built in, so you'll have to do it yourself or hope Xero really gets on top of this soon.

**Comment by james-purr** [comment]
appreciate the swift response guys, I realised this was probably an API issue but I've never had much luck getting response from them so I thought I'd just check. I'll dig and try and get a failsafe retry implemented.

**Comment by nnc** [comment]
Oh and, when debugging these HTTP level issues, `http_logger` gem is a huge help in seeing what exactly is being sent to and received from Xero API.

**Comment by CloCkWeRX** [comment]
> this was probably an API issue

Going to close this one off for now then :)
