### ISSUE TITLE
Sales Quotes In Xero

### ISSUE THREAD

**Issue by charlietarr1** [waynerobinson/xeroizer#321]
Hi all, 

Is it possible to create quotes in Xero using xeroizer? 

It seems this is an essential part of tracking inventory in xero, as part of a sales order process. 

Thanks, 

Charlie

**Comment by SylarRuby** [comment]
I think you mean[ Purchase Order](https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/purchase_order.rb). If so then yes.

**Comment by charlietarr1** [comment]
Thanks for your response. 

I use Purchase Order as part of the purchase order process. 

But need to raise Quotes as part of the sales order process. 

They are separate things.

**Comment by SylarRuby** [comment]
Sorry I havent seen a Model for that. You may have to monkey patch your own Quote Model or request a PR if you have coded your own. Regarding PRs not sure you'd have any luck as people seem to be busy. Like most others, fork this repo and implement your own. Should be easily enough.

**Comment by SylarRuby** [comment]
@charlietarr1 I've looked into it and it's not possible witj Xero. So this is why this gem has not implemented it. See here: https://community.xero.com/developer/discussion/8021506

**Comment by charlietarr1** [comment]
Thanks for the info. Appreciate your time.

**Comment by charlietarr1** [comment]
Follow up question in light of previous responses:

Without being able to access quotes via the API, is there any way of determining available stock levels.

Is there a work around that enables developers to check the value of: Count On Hand - In Committed Quotes?

**Comment by SylarRuby** [comment]
Use your magic with [this](https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/item.rb) (`quantity_on_hand`).

**Comment by charlietarr1** [comment]
Thanks for quick response. 

I can access the value of quantity_on_hand but I am not able to access the value of 'in_commited_quotes'. 
 
Therefore I am unable to deduct one from the other to get the available stock level.

**Comment by SylarRuby** [comment]
What you're after is not made available via the xero api.

**Comment by charlietarr1** [comment]
I feared that may be the case. 

Was hoping for a workaround of some kind but seems this is a blocker to effectively managing stock levels.

**Comment by CloCkWeRX** [comment]
Let's keep an eye on https://developer.xero.com/documentation/api/quotes and reopen this when/if it becomes available
