### ISSUE TITLE
Contact missing discount attribute

### ISSUE THREAD

**Issue by balmoral** [waynerobinson/xeroizer#322]
Contact does not include Discount attribute

**Comment by SylarRuby** [comment]
This is not an issue. If your just asking a question you sentence is correct. It's on line item

**Comment by balmoral** [comment]
Apologies - should have been more explicit - this is not a question.

The API defines an element named 'Discount' which is the default default discount for a Contact, however, the Ruby Contact model does not define a corresponding `decimal :discount` attribute.

I am not referring to line item. In fact in order to set the default discount in a line item I require the default discount for the Contact.

Hope this clarifies the issue.
