### ISSUE TITLE
Account update errors: Cannot update account details and STATUS on the same request

### ISSUE THREAD

**Issue by matsumonkie** [waynerobinson/xeroizer#324]
First thing first, thanks for this awesome gem !

I have this issue with the accounts. Anytime I try to update an account, I run into an error.

```
account = client.Account.all.first # will succeed 
account.save # will throw a validation error
```

```
Xeroizer::ApiException: ValidationException: A validation exception occurred 
 Generated by the following XML: 
 <ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>10</ErrorNumber>
  <Type>ValidationException</Type>
  <Message>A validation exception occurred</Message>
  <Elements>
    <DataContractBase xsi:type="Account">
      <ValidationErrors>
        <ValidationError>
          <Message>**Cannot update account details and STATUS on the same request**</Message>
        </ValidationError>
      </ValidationErrors>
      <AccountID>xxx</AccountID>
      <Code>xxx</Code>
      <Name>xxx</Name>
      <Status>ACTIVE</Status>
      <Type>SALES</Type>
      <TaxType>OUTPUT</TaxType>
      <Class>REVENUE</Class>
      <EnablePaymentsToAccount>false</EnablePaymentsToAccount>
      <ShowInExpenseClaims>false</ShowInExpenseClaims>
      <ReportingCode>REV</ReportingCode>
      <ReportingCodeName>Revenue</ReportingCodeName>
    </DataContractBase>
  </Elements>
</ApiException>
from /home/iori/.gem/ruby/2.2.5/gems/xeroizer-2.16.4/lib/xeroizer/http.rb:180:in `handle_error!'
```

According to the Xero developer documentation

> Limitations
> 
> Accounts of type ‘BANK’ cannot be updated (vote here)

my Account is of type 'SALES'

> You can only update accounts one at a time (i.e. you’ll need to do multiple API calls to update many accounts)
> You cannot update the status to archived (see below) when also updating other values

I'm not even modifying the account, just retrieving it and saving it. 

Am I doing something wrong ?

**Comment by malikilam** [comment]
I am running into the same sort of issue with Bank Transactions.  What I have found is that they cannot be updated if they are initially retrieved as part of an "All" request.  So, in your example, if you were to select get the account_id for your first account using "all" (combined with the "first" method) and then retrieve the very same record using the account id with a "find" request, then the update  (using save) would work:

account_instance1 = client.Account.all.first
account_instance2 = client.Account.find(account_instance1.account_id)
account_instance2.status = "DELETED"  # for example
account_instance2.save

That seems to work, even though account_instance1 and account_instance2 appear to be identical (just retrieved differently).

**Comment by rjaus** [comment]
Hey @matsumonkie I've made some changes to the accounts model. It now supports updating an account, which first remove the status.  It also supports changing the status through an .archive! method.

https://github.com/waynerobinson/xeroizer/pull/418
