### ISSUE TITLE
Has Payroll Employee API  been implemented?

### ISSUE THREAD

**Issue by JuanLUJoanne** [waynerobinson/xeroizer#327]
Hi,

i used xeroizer as Xero integration gem for Payroll Employee, I want to get the payroll employee list.

below is my code:

`@xero_client = Xeroizer::PublicApplication.new(ENV["XERO_OAUTH_CONSUMER_KEY"],
                                                       ENV["XERO_OAUTH_CONSUMER_SECRET"])
      @xero_client.authorize_from_request(session[:request_token],
                                          session[:request_secret],
                                          :oauth_verifier => params[:oauth_verifier])

      session[:xero_auth] = { :access_token => @xero_client.access_token.token,
                              :access_secret => @xero_client.access_token.secret }

      session[:request_token] = nil
      session[:request_secret] = nil
      payroll = @xero_client.Payroll
      employees = payroll.Employee
      render json: employees`

But I got no method error, Could you check whether this API has been implemented?

undefined method `Payroll' for #<Xeroizer::PublicApplication:0x007fd55e2aa1d0>

**Comment by SylarRuby** [comment]
Could you close this issue? Payroll is not available in this gem. Depending on your country, the payroll api is not ready: https://developer.xero.com/documentation/api/employees/

**Comment by JuanLUJoanne** [comment]
OK, got this, thank you. i closed this issue.
