### ISSUE TITLE
signature_invalid:Failed to validate signature

### ISSUE THREAD

**Issue by sampathaya** [waynerobinson/xeroizer#329]
Hi,

I'm getting "signature_invalid:Failed to validate signature" error. It happened suddenly. it was working fine for couple of days and my app was working very smoothly. 

today started to get this error. and please let me know how to fix.

thanks

**Comment by nnc** [comment]
This seems to be a Xero API issue, as we also started getting these errors an hour or two ago.

Still waiting on a reply from Xero API support to see what is happening, but it doesn't look like it has anything to do with Xeroizer gem.

**Comment by tatey** [comment]
https://github.com/waynerobinson/xeroizer/issues/329

**Comment by dclelland** [comment]
Getting this error too from around 11:20 am today.

May have happened since we restarted our server last night but can't say that was the trigger for sure.

**Comment by dclelland** [comment]
Has this spontaneously resolved itself for everybody else?

**Comment by nnc** [comment]
Yes, it has. This was a Xero API issue that was resolved long ago.

Please close this issue.

**Comment by benpetro** [comment]
I don't think it's a XERO issue, on the current release 2.16.5 I'm getting this error, but if I use tag 2.15.4, I connect fine.  The error I'm getting is: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed

**Comment by waynerobinson** [comment]
This is probably because your own machine's certificates are invalid or
your instance of ruby is referring to the wrong certificate file based on
how you installed ruby on your machine.

**Comment by benpetro** [comment]
I just started receiving errors yesterday on Dec 6th, no machine updates or server reboots for at least a month, using the XERO API multiple times a day.  Which leads me to believe it IS a XERO issue, however I was just thrown when I rolled back to a previous release, and everything works fine. I'll keep looking.

**Comment by adamrainsby** [comment]
We have also started getting SSL errors since yesterday.

Xero don't seem to be aware of an issue https://twitter.com/Xero/status/806411086270525440

**Comment by adamrainsby** [comment]
Bumping the version to 2.16.5 seems to have fixed it. Thanks @waynerobinson

**Comment by HassanAkbar** [comment]
I'm getting "signature_invalid:Failed to validate signature" error. It has started to happen from a week before that everything was working perfectly with 2.16.5 and I had monkeypatched this commit from almost 6 months.
https://github.com/waynerobinson/xeroizer/commit/052723aa279d32e150fcf82cf1aad936f08936f4

It has started failing with the same error

**Comment by JuanLUJoanne** [comment]
Hi, I got the same error. it works for a while, but just suddenly does not work in my local.
I am on xeroizer (2.18.1). I tired use `GET` action to Xero API then it worked in yesterday(and `POST` action too). but it came back to not work today. I am sure used the correct Consumer Key, Secret, public key certificate in XERO app setting. Could you help on this?

**Comment by simmerz** [comment]
I'm getting this same issue some hours after a deploy. Initially it works fine, and then it just stops.
