### ISSUE TITLE
Possible to determine Organisation linked to?

### ISSUE THREAD

**Issue by lesliev** [waynerobinson/xeroizer#331]
Is it possible to determine which Organisation a user picked after they complete the authorization process? 

If a user accidentally picks the wrong organisation, that could have serious consequences in my app, because data from the newly chosen organisation would get merged with the previous one. Is there a way to detect and prevent this situation?

**Comment by lesliev** [comment]
It seems that the Organisation API call returns only the single Organisation linked to. Is that always the case?

**Comment by waynerobinson** [comment]
I believe so.

**Comment by lesliev** [comment]
Thanks Wayne!

**Comment by buggy** [comment]
The access tokens issued via the OAuth process are for the organisation, not the user. As a result you will only ever get one organisation returned.
