### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by BENGMN** [waynerobinson/xeroizer#332]
I have a private application that has been connecting to Xero all year and suddenly has started returning an OpenSSL::SSL::SSLError.

Specifically I am seeing the following message 

> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Any help would be greatly appreciated. I have diligently followed all of the steps located in the README.

**Comment by waynerobinson** [comment]
Fixed today. Please update to version 2.16.5.
