### ISSUE TITLE
PrivateApplication can take a string, not just a file path

### ISSUE THREAD

**Issue by tatey** [waynerobinson/xeroizer#338]
Hello,

Firstly, thank you for this library :+1: ❤.

Currently the signature for `Xeroizer::PrivateApplication.new` only takes a path to the bundled certificate.

``` ruby
Xeroizer::PrivateApplication.new(key, secret, "/path/to/ca")
```

Our application is hosted on Heroku and we use an environment variable to distribute the certificate. We don't have a path, but we do have a string. Under the hood `OAuth::Consumer.new` can take either a path or a string. Using this knowledge we can work around Xeroizer by setting the path to `nil` and then passing our `private_key:` as an option.

``` ruby
Xeroizer::PrivateApplication.new(key, secret, nil, private_key: ENV["XERO_PRIVATE_KEY"])
```

It's great that we have a work around, but it took me some time to figure out. If it's OK with the @waynerobinson and the other maintainers I would like to change the signature so it's obvious for the next person.

``` ruby
# Path
Xeroizer::PrivateApplication.new(key, secret, private_key_file: "/path/to/key")

# String
Xeroizer::PrivateApplication.new(key, secret, private_key: ENV["XERO_PRIVATE_KEY"])
```

And raise an `ArgumentError` if neither of these keys are given. This would be a breaking change which is why I'm asking for your blessing first. I'm also open to alternatives.

Will wait for https://github.com/waynerobinson/xeroizer/pull/337 and https://github.com/waynerobinson/xeroizer/pull/336 to be merged before submitting a patch.

**Comment by tatey** [comment]
I'm also happy to update documentation as a part of doing the work 😄

**Comment by waynerobinson** [comment]
I have some issues in such a large API change for minimal benefit. Adding the two named params is fine and making the standard path optional might be a better solution. 

This makes it backwardly compatible with the existing solution whilst allowing you to use the new one.

**Comment by CloCkWeRX** [comment]
Going to close based on the last comment
