### ISSUE TITLE
PartnerApplication is not working

### ISSUE THREAD

**Issue by polimorfico** [waynerobinson/xeroizer#340]
According to Xero support: 

> Please note we have recently changed an element of the Xero Partner application connection methods. It won't affect you, but there may be parts of our SDKs that make reference to this, specifically:
>- Ensure you are communicating with our API using "https://api.xero.com/" and not "https://api-partner.network.xero.com"
>- Any references to Entrust SSL certificates when creating an instance of http client object may need to be removed from your code.

So endpoints must be updated and SSL certificates are not longer needed.

**Comment by nnc** [comment]
Hi @polimorfico, can you please give me a link to Xero announcement regarding this change? I was unable to find it on https://developer.xero.com

**Comment by polimorfico** [comment]
They just sent us the following message when our app was accepted in their partners program:
![xero-email](https://cloud.githubusercontent.com/assets/431649/21461334/9de4953e-c948-11e6-9379-086f4ae85ec0.png)
