### ISSUE TITLE
Unable to post a Payment

### ISSUE THREAD

**Issue by BENGMN** [waynerobinson/xeroizer#365]
Anyone else having an issue creating a payment against an invoice using the API? According to the API it seems a PUT request is necessary to create a payment, but in the source code I see the       set_permissions :read, :write, NOT update on the Payment Object.

Any help or pointers are appreciated.

**Comment by nickooolas** [comment]
@BENGMN 

Here's a working example for me (rpvia

#### Initialise Xeroizer Client
```
client = Xeroizer::PrivateApplication.new(ENV['XERO_DEMO_CONSUMER_KEY'], ENV['XERO_DEMO_CONSUMER_SECRET'], "#{Rails.root}/config/ssh_keys/privatekey.pem")
```

#### Build bare bones Payment
```
payment = client.Payment.build
```

#### Associate it with an existing Invoice / account code (seems counter intuitive to `build` an  existing `Invoice` or `Account`  when it already exists, but it works trust me ;) 

```
payment.build_account(id: '234243-849a-42342-9a31-57b7eac713d7')
payment.build_invoice(id: '6sdf3243e-9b37-41c5-9c87-1324sdfs3')
payment.amount = 900.00
payment.date = Date.today
```

#### Save it, should return `true`
```
payment.save #=> true
```

`Payment ID #=> 32h4f2g34j-92342i3k-41c5-9c87-1234l2n3l`

#### Can even then delete it, but this is also a bit different to what you might expect, need to `POST`, so easiest to do this - making sure that the id of the newly built payment, is actually an existing one.

```
pmt = client.Payment.build(id: '32h4f2g34j-92342i3k-41c5-9c87-1234l2n3l', status: 'DELETED')
```

**Comment by rjaus** [comment]
Added an example to the README: https://github.com/waynerobinson/xeroizer#example-use-cases
