### ISSUE TITLE
Can't update an invoices status to authorised 

### ISSUE THREAD

**Issue by mtdurling** [waynerobinson/xeroizer#37]
I have some code which mass approves draft invoices in Xero which has recently stopped working. I can't seem to get it to work, even with a simple example using the rails console and a Xero demo company.

As shown in the code sample below:
- I pull down a draft invoice from the demo company,
- Attempt to set the status to "AUTHORISED"
-  Then save it.

This returns true and doesn't return any errors. When I pull down the invoice a second time, the status doesn't seem to have been updated.

I'm pretty sure I was able to do this last month! I'm not sure if I'm going crazy or I'm doing something incorrectly.

``` ruby
irb(main):024:0> xero_invoice = xero.Invoice.first(:where => {:reference => 122343434})
=> #<Xeroizer::Record::Invoice :contact: #<Xeroizer::Record::Contact :contact_id: "f4bcc6c9-d955-4466-a54d-92bd02039a3c", :name: "Arabica Cafe">, :date: Thu, 11 Oct 2012, :due_date: Mon, 15 Oct 2012, :branding_theme_id: "7889a0ac-262a-40e3-8a63-9a769b1a18af", :status: "DRAFT", :line_amount_types: "Exclusive", :sub_total: #<BigDecimal:7fa954b35830,'0.25E3',9(18)>, :total_tax: #<BigDecimal:7fa954b353a8,'0.375E2',18(18)>, :total: #<BigDecimal:7fa954b34fe8,'0.2875E3',18(18)>, :updated_date_utc: 2012-10-02 03:33:05 +1300, :currency_code: "NZD", :type: "ACCREC", :invoice_id: "71535ce7-c215-4804-97db-8830e74cf229", :invoice_number: "INV-0040", :reference: "122343434", :amount_due: #<BigDecimal:7fa954b49510,'0.2875E3',18(18)>, :amount_paid: #<BigDecimal:7fa954b49010,'0.0',9(18)>>
irb(main):025:0> xero_invoice.status = "AUTHORISED"
=> "AUTHORISED"
irb(main):026:0> xero_invoice.save
=> true
irb(main):027:0> xero_invoice = xero.Invoice.first(:where => {:reference => 122343434})
=> #<Xeroizer::Record::Invoice :contact: #<Xeroizer::Record::Contact :contact_id: "f4bcc6c9-d955-4466-a54d-92bd02039a3c", :name: "Arabica Cafe">, :date: Thu, 11 Oct 2012, :due_date: Mon, 15 Oct 2012, :branding_theme_id: "7889a0ac-262a-40e3-8a63-9a769b1a18af", :status: "DRAFT", :line_amount_types: "Exclusive", :sub_total: #<BigDecimal:7fa9564ca930,'0.25E3',9(18)>, :total_tax: #<BigDecimal:7fa9564ca4a8,'0.375E2',18(18)>, :total: #<BigDecimal:7fa9564ca110,'0.2875E3',18(18)>, :updated_date_utc: 2012-10-02 03:34:59 +1300, :currency_code: "NZD", :type: "ACCREC", :invoice_id: "71535ce7-c215-4804-97db-8830e74cf229", :invoice_number: "INV-0040", :reference: "122343434", :amount_due: #<BigDecimal:7fa9564cfca0,'0.2875E3',18(18)>, :amount_paid: #<BigDecimal:7fa9564cf7a0,'0.0',9(18)>>
```

Am I missing something here?

**Comment by stevenou** [comment]
Just curious if code was ever implemented to skip `download_complete_record!`? I just ran into this issue and discovered that saving twice worked (I guess on the first save it downloads the complete record, and then on the second save it actually saves). 

Nonetheless, when changing the status of 1000 records, `download_complete_record!` would cause it to hit rate limits, so the ability to skip `download_complete_record!` would be very helpful. That way we can update 1000 records in a batch_save and not have rate limit issues. 

In my opinion, it would make sense to implement it in the way Rails has the `includes` or `preload` methods. That way when we select the entries, we can choose whether to also load associations or not?
