### ISSUE TITLE
Credit Note 'attach_data' Method not working in latest master

### ISSUE THREAD

**Issue by nickooolas** [waynerobinson/xeroizer#370]
Hi Guys,

I've noticed that the `attach_data` method, and in fact any Attachment Extensions doesn't seem to be working in the latest master branch for `CreditNote` but working fine as expected for `Invoice`

Could you confirm this is the case, or do I have something else going on with my versions? 

Cheers,

Nick

**Comment by CloCkWeRX** [comment]
Are you able to create a unit test or similar to demonstrate the difference?

**Comment by CloCkWeRX** [comment]
Closing due to lack of feedback, we'll reopen if other reports come in
