### ISSUE TITLE
In query to find multiple contacts

### ISSUE THREAD

**Issue by hardikjain90** [waynerobinson/xeroizer#375]
Hi,
I want to know the ways to find multiple contacts using account_number field.
Something like below but it raised the exception.
Let me know some alternate ways for it.
`xero.Contact.all(where: { account_number: ['10000', '10002'] })`

Thanks and Regards,
Hardik Jain

**Comment by rjaus** [comment]
Hey @hardikjain90, this isn't possible via the Xero API.  You could request the feature: https://xero.uservoice.com/

Alternatively I'd suggest paginating through all the contacts and filtering on your end (or make a separate calls
```ruby
xero.Contact.all(where: { account_number: '10000' })
xero.Contact.all(where: { account_number: '10002' })
```

It depends how many contacts you're trying to retrieve.
