### ISSUE TITLE
issue to access partner application module

### ISSUE THREAD

**Issue by karpit** [waynerobinson/xeroizer#378]
xero_client = Xeroizer::PartnerApplication.new(XERO_CONFIG[Rails.env]["oauth_consumer_key"], XERO_CONFIG[Rails.env]["oauth_consumer_secret"], "#{Rails.root}/privatekey.pem")

I am running above on rails console but i am getting below error.

ArgumentError: wrong number of arguments (given 3, expected 5..6)
from /home/anil/.rvm/gems/ruby-2.3.3@owner/gems/xeroizer-2.16.5/lib/xeroizer/partner_application.rb:20:in `initialize'

Please help me resolve this issue and guide me as well that how to use it.

**Comment by nnc** [comment]
Gem version 2.16.5 is a bit old now, and `PartnerApplication#initialize` signature has beed changed since 2.16.5 was released, so README is talking about the latest, as yet unreleased, version of Xeroizer.

I'd recommend you use the latest version from GitHub until new gem version is released.

```ruby
# You may have this already in your Gemfile
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'xeroizer', github: 'waynerobinson/xeroizer'
```

**Comment by karpit** [comment]
Thanks for your response.

**Comment by karpit** [comment]
Thanks above issue has been fixed.
Now I am getting another issue with partner application module.'
[23] pry(main)> request_token = xero_client.request_token(:oauth_callback => 'http://localhost:3000')
OAuth::Unauthorized: 400 Bad Request
/oauth-0.5.3/lib/oauth/consumer.rb:236:in `token_request'

I am getting this error, please provide me solution for it.

**Comment by nnc** [comment]
Try using `http://127.0.0.1:3000` instead of `http://localhost:3000`.

**Comment by karpit** [comment]
Thanks for your reply, but I am partner application issue.

I am unable to get approval for creating Partner application for xero.

Do you have any idea about it.

Thanks,
Arpit

**Comment by nnc** [comment]
Sorry, but I don't think anyone here can help you with that.

You'll need to go through [Xero's process](https://developer.xero.com/partner/app-partner) for becoming an app partner, and only Xero support can help get your application approved.

If you already have a partner application on Xero, and can't get it to work with Xeroizer you'll need to post here or link to your full Xero integration code, and someone may be able to help with that.

**Comment by karpit** [comment]
Thanks for your support and suggestion.
I am trying connect with xero support team to approve the Partner
Application.

Thanks

**Comment by rjaus** [comment]
Hey @karpit , @ncc is right, Partner App access requires your application to go through our certification process.  That starts here: https://developer.xero.com/partner/app-partner

You'll need to build out your integration with the Public App until you have something you can demonstrate to us.  An [MVP](https://www.quora.com/What-is-a-minimum-viable-product) would be suitable, but it needs to utilise the API.

**Comment by karpit** [comment]
Thanks for your response.

**Comment by rjaus** [comment]
New version has been released and pushed to RubyGems: https://rubygems.org/gems/xeroizer/versions/2.17.0

This version includes the deprecation of entrust certs and the partner api url change: https://github.com/waynerobinson/xeroizer/releases/tag/v2.17.0
