### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pareeohnos** [waynerobinson/xeroizer#379]
I'm trying to integrate Xeroizer into an application, and need access to the organisation ID as the app will be supporting multiple organisations and needs to differentiate them. There is a pull request merged, however it's only available on the master branch.

I've switched the app over to master and am now able to use the organisation_id method, however I never feel that comfortable running a production system with gems pointing to the git repository.

Is there any plan on releasing a new version with all the changes since the previous release?

**Comment by toxaq** [comment]
Refer #361

**Comment by pareeohnos** [comment]
ah sorry, completely missed that :(
