### ISSUE TITLE
Rubygems version no longer workers

### ISSUE THREAD

**Issue by ryanwilliams** [waynerobinson/xeroizer#388]
As of today Xero discontinued the old API urls. I see you fixed this 10 months ago, but you haven't pushed the fix to Rubygems. 

Do plan on updating the rubygems version?

This commit is the fix:  https://github.com/waynerobinson/xeroizer/commit/052723aa279d32e150fcf82cf1aad936f08936f4

**Comment by luanht** [comment]
Same problem. Im migrating my app to use partner application.
I've had to set github url in my Gemfile for now:
```
gem 'xeroizer', github: 'waynerobinson/xeroizer'
```

**Comment by rjaus** [comment]
New version has been released and pushed to RubyGems: https://rubygems.org/gems/xeroizer/versions/2.17.0

This version includes the deprecation of entrust certs and the partner api url change: https://github.com/waynerobinson/xeroizer/releases/tag/v2.17.0
