### ISSUE TITLE
Unable to access some fields from Xeroizer ActiveRecord result

### ISSUE THREAD

**Issue by andthomas** [waynerobinson/xeroizer#396]
Hello

When I try to access :address_type, :address_line1 or :address_line2 of the following Xeroizer ActiveRecord result I get a NoMethodError. Is this an existing error in Xeroizer?

```
@xero_clients[1].addresses[0]
=> #<Xeroizer::Record::Address :address_type: "POBOX", :address_line1: "L9 BWA Tower\n", :address_line2: "150 Bourke Street", :city: "Melbourne", :postal_code: "3133">

@xero_clients[1].addresses[0].address_type
NoMethodError: undefined method 'address_type' for #<Xeroizer::Record::Address:0x007fed539d3f58>
from (pry):3:in `index'

@xero_clients[1].addresses[0].postal_code
=> "3133"

```

Thanks

**Comment by rjaus** [comment]
Any chance you can run the query again and provide the Raw response.

**Comment by andthomas** [comment]
So in my controller I make a Xeroizer API call: 

`client = Xeroizer::PrivateApplication.new(Rails.application.secrets.XERO_OAUTH_CONSUMER_KEY, Rails.application.secrets.XERO_OAUTH_CONSUMER_SECRET, "privatekey.pem")

@xero_clients = client.Contact.all(:where => {:is_customer => true})

binding.pry`

Then in pry when I access a record I get: 

`[30] pry(#<ClientsController>)> @xero_clients[4]
=> #<Xeroizer::Record::Contact :contact_id: "41a42865-f15a-4fa1-b643-47877608f557", :contact_status: "ACTIVE", :name: "Boom FM", :email_address: "boom@radiooz.co", :skype_user_name: "+123demo", :addresses: [#<Xeroizer::Record::Address :address_type: "STREET", :address_line1: "Radio OZ House\n", :address_line2: "43 Ballarat Highway\n", :city: "Melbourne", :postal_code: "3133">, #<Xeroizer::Record::Address :address_type: "POBOX", :address_line1: "Radio OZ House\n", :address_line2: "P O Box 5768", :city: "Melbourne", :region: "VIC", :postal_code: "3133">], :phones: [#<Xeroizer::Record::Phone :phone_type: "DDI">, #<Xeroizer::Record::Phone :phone_type: "DEFAULT", :phone_number: "3314321", :phone_area_code: "03">, #<Xeroizer::Record::Phone :phone_type: "FAX">, #<Xeroizer::Record::Phone :phone_type: "MOBILE">], :updated_date_utc: 2017-11-02 18:03:42 UTC, :is_supplier: false, :is_customer: true, :has_attachments: false>`

I can access an address: 
`[33] pry(#<ClientsController>)> @xero_clients[4].addresses[1]
=> #<Xeroizer::Record::Address :address_type: "POBOX", :address_line1: "Radio OZ House\n", :address_line2: "P O Box 5768", :city: "Melbourne", :region: "VIC", :postal_code: "3133">
`

And for each entry I've tested I can't access address_type, address_line1, address_line2. I get:

`[34] pry(#<ClientsController>)> @xero_clients[4].addresses[1].address_type
NoMethodError: undefined method address_type' for #<Xeroizer::Record::Address:0x007fd67b6f71e8>
from (pry):34:in index'`

But for city, region and postal_code i can access the details in the record:

`[35] pry(#<ClientsController>)> @xero_clients[4].addresses[1].postal_code
=> "3133"`

**Comment by rjaus** [comment]
Hey @andthomas it looks like the fields you've mentioned have been given internal_names in order to make it a little easier to read.

https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/address.rb#L16

Basically just removing the address portion each time.
