### ISSUE TITLE
Add `save!` method

### ISSUE THREAD

**Issue by pareeohnos** [waynerobinson/xeroizer#402]
Whilst writing an app with Xeroizer, I came into a number of cases where attempting to save a record resulted in an exception being raised, so I assumed this was the case all the time. I have since noticed that in-line with ActiveRecord, the `save` method simply returns true or false. If however there is an unhandled case by Xeroizer, it will still raise an exception (as I found previously)

Would it be better to introduce a `save!` method where all failed saves result in an exception? I have a bunch of code now that assumes an exception will be raised on validation failures which now needs modifying (my fault entirely) but if there were a `save!` method, this would not be needed

**Comment by nnc** [comment]
I've been burned by this inconsistent behavior in the past, and would also welcome the addition of `save!` method.

**Comment by rjaus** [comment]
Sounds good, @pareeohnos do you want to submit a PR?

**Comment by pareeohnos** [comment]
Sure thing
