### ISSUE TITLE
Dynamic string Value in where clause not working

### ISSUE THREAD

**Issue by rishitandon** [waynerobinson/xeroizer#408]
Hi ,
Can you please advice how to get dynamic string parsing will work in where clause

How do you inject dynamic string values into this structure

eg :where => 'Name.StartsWith("#{@supplier.name}")' wont work

Thanks

**Comment by vergilet** [comment]
Have related issue.
Cannot get the account by the last 4 numbers:

```ruby
client.Account.all(:where => 'BankAccountNumber.EndsWith("6789")')
```
Terminal 
>Xeroizer::Http::BadResponse: Unknown response code: 500

Xero API Preview tool
```xml
<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>500</ErrorNumber>
  <Type>UnknownErrorException</Type>
  <Message>An error occurred in Xero. Check the API Status page http://status.developer.xero.com for current service status. Contact the API support team at api@xero.com for more assistance.</Message>
</ApiException>
```

**Comment by rishitandon** [comment]
After lot iteration able to get this one working for dynamic params 

@xero_contacts = @xero_x.Contact.all(:where => "Name.Contains(\"#{params[:name]}\")")
@xero_contacts = @xero_x.Contact.all(:where => "FirstName == (\"#{params[:first_name]}\")")

@vergilet ,Check if it works in your scenario

**Comment by vergilet** [comment]
@rishitandon, your case I handled with slash before quotes:

```ruby
date = "2018-01-20"
client.Invoice.all(where: "Date>=DateTime.Parse(\"#{date}\")").count
```  

But my problem still appears ...

**Comment by rjaus** [comment]
@vergilet your issue here
```ruby
client.Account.all(:where => 'BankAccountNumber.EndsWith("6789")')
```
Is not related to the gem, but rather the API itself.  The field BankAccountNumber throws an error 500 when any filter functions are used.  Not clear why, I'll submit a bug report internally.

@rishitandon the below example works for me as well.  I'm assuming this resolved your issue.
```ruby
date = "2018-01-20"
client.Invoice.all(where: "Date>=DateTime.Parse(\"#{date}\")").count
```
