### ISSUE TITLE
Release 2.18.0

### ISSUE THREAD

**Issue by CloCkWeRX** [waynerobinson/xeroizer#415]
It's chock full of goodness: https://github.com/waynerobinson/xeroizer/milestone/3?closed=1

Unfortunately, my macbook is dead right now so I don't have a ruby env/can't publish a gem. @rjaus whaddayathink?

**Comment by rjaus** [comment]
Agreed, it's about time.  There may be a few more updates next week, so I'll hold off for another 1 - 2 weeks and then push a new version.

**Comment by nnc** [comment]
2.18 was released, so please close this to avoid confusion.

Thanks!
