### ISSUE TITLE
Issue with Partner Application

### ISSUE THREAD

**Issue by arialblack14** [waynerobinson/xeroizer#421]
My development app has been approved as a Partner App. I was connecting just fine as a Public App but now I keep getting this error:
```
A JSON::ParserError occurred in #:

  784: unexpected token at 'oauth_problem=signature_method_rejected&oauth_problem_advice=Partner%20applications%20must%20use%20RSA-SHA1%20signature%20method'
```
Here is my code:
```
class ConnectionAuthentication < ActiveRecord::Base
  def self.create_from_omniauth(params, user, provider)
    case provider.name
      when 'xero'
      binding.pry
        token_expires_at = params['extra']['access_token'].params['oauth_expires_in'] ?
            Time.now + (params['extra']['access_token'].params['oauth_expires_in']).to_i : nil

        self.destroy_previous_connections(user)

        create(
            authentication_provider_id: provider.id,
            user_id: user.id,
            uid: params['uid'],
            token: params['extra']['access_token'].token,
            secret: params['extra']['access_token'].secret,
            token_expires_at: token_expires_at,
            params: params,
        )
     ....
  end
end

connection = ConnectionAuthentication.current_connection(current_user)

client = Xeroizer::PartnerApplication.new(Devise.omniauth_configs[:xero].strategy.consumer_key,
		                                               Devise.omniauth_configs[:xero].strategy.consumer_secret,
		                                               "#{Rails.root}/certs/privatekey.pem",
		                                               signature_method: 'RSA-SHA1',
		                                               rate_limit_sleep: 2,														 
                                                              before_request: ->(request) {																			 
                                                                 request.headers.merge! "User-Agent" => ENV['XERO_USER_AGENT']																									 })

client.authorize_from_access(connection.token, connection.secret)
```

**Comment by rjaus** [comment]
Which version of the gem are you using?

Can you confirm your private key is correct one (the private key of the public key you uploaded to dev portal)

Can you try the same request without setting/modifying the UserAgent string?

**Comment by rjaus** [comment]
I think it's probably the way you're setting the UserAgent string.  Params needs to be signed in the correct order.

If you set it like this, it should work.
```ruby
@headers = {"User-Agent" => "Xeroizer/2.15.5"}
@application = Xeroizer::PublicApplication.new(CONSUMER_KEY, CONSUMER_SECRET, :default_headers => @headers)
```

**Comment by arialblack14** [comment]
@rjaus Thank you for your response.
I will try changing the UserAgent change.
The public/private keys are correct for sure.
I even made a new pair and tried again.
I will let you know asap.

**Comment by arialblack14** [comment]
I am using the latest version of the gem (2.18.1).
I still get the same error message that I should be using RSA-SHA1 signature method.
Any ideas what is going on?

**Comment by rjaus** [comment]
Hey @arialblack14 I've been unable to recreate this issue.

Xeroizer::PartnerApplication should default to using RSA-SHA1, and on top of that you're specifying it as well.  So I'm not sure how requests are being made without it.

Are you sure, somewhere else in your code, that it's not still using the Public App type? Public App is the only Xero API App Type that doesn't use RSA-SHA1.

**Comment by arialblack14** [comment]
Hello @rjaus, I was thinking the exact same thing so after a re-write it is working.
Thank you for the help!
