### ISSUE TITLE
History and Notes API

### ISSUE THREAD

**Issue by adityashedge** [waynerobinson/xeroizer#424]
Is there a wrapper over the History and Notes API?

End Point: `https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/history`
Documentation: https://developer.xero.com/documentation/api/history-and-notes

**Comment by rjaus** [comment]
Has been added: https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/history_record.rb
