### ISSUE TITLE
Save boolean value to true in Contact elements does not work

### ISSUE THREAD

**Issue by haroldus-** [waynerobinson/xeroizer#430]
try to set the IsCustomer or IsSupplier element to true:
```
contact = Contact.find('b7206cab-etc...')
contact.is_supplier = true
contact.save
```

now retrieve contact from the API and observe that IsSupplier is still `false`

**Comment by CloCkWeRX** [comment]
Check out:
https://developer.xero.com/documentation/api/contacts

IsSupplier | true or false – Boolean that describes if a contact that has any AP invoices entered against them. Cannot be set via PUT or POST - it is automatically set when an accounts payable invoice is generated against this contact.
-- | --
IsCustomer | true or false – Boolean that describes if a contact has any AR invoices entered against them. Cannot be set via PUT or POST - it is automatically set when an accounts receivable invoice is generated against this contact.
