### ISSUE TITLE
Credit Note line items with nil line_item_id

### ISSUE THREAD

**Issue by malaimo** [waynerobinson/xeroizer#431]
Line Items from Credit Notes has line_item_id = nil, while Invoice line items has xero line_item_id OK.

Credit Notes line items should also have their corresponding Xero ID on line_item_id

**Comment by CloCkWeRX** [comment]
Able to provide a reproduce script or unit test for this, with API responses?

**Comment by rjaus** [comment]
CreditNotes do not provide an LineItemId via the API, therefore it won't be present in the SDK: https://developer.xero.com/documentation/api/accounting/creditnotes#get-creditnotes
