### ISSUE TITLE
Add YEARLY as a valid Schedule unit

### ISSUE THREAD

**Issue by julienchabanon** [waynerobinson/xeroizer#432]
Hi,

I am not sur if this is related to xero or xeroizer but on update a repeating invoice, I get 500 by xero.
Also, for value: schedule.unit, 'YEARLY' should be a correct value:
https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/schedule.rb#L10

Thanks

**Comment by CloCkWeRX** [comment]
https://developer.xero.com/documentation/api/types
![image](https://user-images.githubusercontent.com/365751/48309197-a175c200-e5c4-11e8-9404-36d30c4bd1e3.png)

Seems like an easy PR; feel free to shoot one in
