### ISSUE TITLE
Sending data containing utf8(emoji) causes a signature invalid error

### ISSUE THREAD

**Issue by robwilliams** [waynerobinson/xeroizer#434]
If a string (i.e. Xeroizer::Record::LineItem#description) that is sent to Xero contains emoji, xero respond with: `signature_invalid:Failed to validate signature` on save. 

Using the Xero UI, if you add a 😜 (or similar) to a line item description it gets stripped out when saving the invoice. Should we sanitise our data before it reaches xeroizer? or is this something that the library should handle? 

I need to handle this in my project either way so I'm willing to add the functionality to this project if it's the right way to go.

**Comment by dmott** [comment]
I'd like to add that this error can be reproduced when putting an emoji in a Contact name as well as a Product name. Using the Xero UI, similar to the Line Items, the Contact Name gets sanitized, however it doesn't seem to sanitize the emojis for the Product name!

I have the same questions as @robwilliams though!

**Comment by CloCkWeRX** [comment]
I'd suggest for now, sanitize prior to inputting content - the xero API rejecting the content as invalid input makes sense, and at most I'd put validation into xeroizer to mirror the report API behaviour.
