### ISSUE TITLE
Is Xeroizer affected by the Xero TLS 1.0 deprecation?

### ISSUE THREAD

**Issue by benpetro** [waynerobinson/xeroizer#435]
https://developer.xero.com/tls1-deprecation

Just enquiring if my app using Xerozier will be affected by this deprecation?  Not even sure if TLS 1.0 applies to this gem, but just wanted to check.

**Comment by rjaus** [comment]
Should be fine, but check out this: https://medium.com/@riley.james/xero-api-tls-1-2-upgrade-guide-for-ruby-c7d65d220082
