### ISSUE TITLE
ContactGroup missing primary key

### ISSUE THREAD

**Issue by hegedus** [waynerobinson/xeroizer#438]
ContactGroup is missing primary key definition:

>> grp = xero.ContactGroup.first(where:{name:'Madgex Customers'})
>> grp.download_complete_record!
Traceback (most recent call last):
        5: from /usr/bin/irb:11:in 'main'
        4: from (irb):3
        3: from /var/lib/gems/2.5.0/gems/xeroizer-2.18.1/lib/xeroizer/record/base.rb:100:in 'download_complete_record!'
        2: from /var/lib/gems/2.5.0/gems/xeroizer-2.18.1/lib/xeroizer/record/model_definition_helper.rb:88:in 'id'
        1: from /var/lib/gems/2.5.0/gems/xeroizer-2.18.1/lib/xeroizer/record/base.rb:54:in '[]'
TypeError (nil is not a symbol nor a string)
>> p grp.id  
Traceback (most recent call last):
        4: from /usr/bin/irb:11:in '<main>'
        3: from (irb):4
        2: from /var/lib/gems/2.5.0/gems/xeroizer-2.18.1/lib/xeroizer/record/model_definition_helper.rb:88:in 'id'
        1: from /var/lib/gems/2.5.0/gems/xeroizer-2.18.1/lib/xeroizer/record/base.rb:54:in '[]'
TypeError (nil is not a symbol nor a string)
>> p grp.contact_group_id
"f8523672-1590-4da4-810f-e5abae97845e"

Adding "set_primary_key :contact_group_id" to "lib/xeroizer/models/contact_group.rb" fixes it, but I'm new to this library, so not sure if that's the best approach.

Thanks,
Peter

**Comment by rjaus** [comment]
Has been resolved
