### ISSUE TITLE
private application: signature_invalid:Failed to validate signature

### ISSUE THREAD

**Issue by JuanLUJoanne** [waynerobinson/xeroizer#446]
Hi, I got the same error. it works for a while, but just suddenly does not work in my local.
I am on xeroizer (2.18.1). I tired use `GET` action to Xero API then it worked in yesterday(and `POST` action too). but it came back to not work today. I am sure used the correct Consumer Key, Secret, public key certificate in XERO app setting. Could you help on this?

**Comment by JuanLUJoanne** [comment]
XeroGateway Request: GET /api.xro/2.0/Invoices/ORC1031
XeroGateway Response (401)
/api.xro/2.0/Invoices/ORC1031
== Response Body

oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature
== End Response Body
Xeroizer::OAuth::UnknownError: signature_invalid:Failed to validate signature
from /Users/juanlu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xeroizer-2.18.1/lib/xeroizer/http.rb:177:in `handle_oauth_error!'

**Comment by simmerz** [comment]
@JuanLUJoanne can you elaborate on what you did to resolve this?
