### ISSUE TITLE
Partner Application: Invalid access_token.secret can still able to do some request and doesn't return any error.

### ISSUE THREAD

**Issue by kevinatflow** [waynerobinson/xeroizer#452]
We just switch from Public to Partner program and when did the testing we tried to change the access_token.secret in the database to be invalid or random string, but it still process the request and it doesn't return any error. 

Before in Public application it returns an error if I changed the secret key and do an api request. But in partner application it fail to validate.

Anyone have tried the same case ? I think this is bug.

**Comment by rjaus** [comment]
Partner App is deprecated: https://github.com/waynerobinson/xeroizer/pull/542
