### ISSUE TITLE
Xeroizer::GenericApplication#payroll NoMethodError

### ISSUE THREAD

**Issue by vladiim** [waynerobinson/xeroizer#455]
`client.payroll` gives the following error: `NoMethodError (undefined method `xero_url=' for #<Xeroizer::PrivateApplication:0x00007fd8ea704ef8>)`

In order to access payroll I'm currently doing the following:
```ruby
xero_client = client.clone
xero_client.instance_variable_set("@xero_url", "https://api.xero.com/payroll.xro/1.0")
payroll = Xeroizer::PayrollApplication.new(xero_client)
```

**Comment by CloCkWeRX** [comment]
Going to close this one for the payroll branch; which... we will land one day.
