### ISSUE TITLE
Help with rspec test.

### ISSUE THREAD

**Issue by ashok1** [waynerobinson/xeroizer#457]
I am trying to write rspec test where I need to mock the xero API calls. Unfortunately I am getting no where with this. Can you provide some suggestions regarding how this can be achieved? Any help will be greatly appreciated.

**Comment by S1rFrancis** [comment]
Have you tried using the VCR gem: https://github.com/vcr/vcr

**Comment by CloCkWeRX** [comment]
Going to close this one as it isn't quite xeroizer specific, VCR is a good recommendation though
