### ISSUE TITLE
Getting expenses for a period of time

### ISSUE THREAD

**Issue by chrisedington** [waynerobinson/xeroizer#462]
Hi,

I'm trying to get the total expenses for a trackingCategoryID / Division for a period of time. 

I wanted to use the "Profit And Loss" report, specifying a DATE RANGE and a TRACKING ID, would that be the right approach? 

I see there is a method @client.ProfitAndLoss -- but I cannot figure out how to pass both the date range and tracking ID? (https://developer.xero.com/documentation/api/reports#ProfitAndLoss)

Alternatively, is there a better way to get the expenses for a division for a time period?

**Comment by CloCkWeRX** [comment]
See also #473

**Comment by CloCkWeRX** [comment]
Its not really supported right now, though pull requests are very welcome

**Comment by dcrtantuco** [comment]
I'm able to specify date range in `ProfitAndLoss` using

```
xero.ProfitAndLoss.get(fromDate: Date.new(2019,4,1), toDate: Date.new(2019,5,1))
```
