### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by edlebert** [waynerobinson/xeroizer#472]
Hi, any plans to release a new version soon?  The last release was a year ago and there have been a lot of important additions since then.

**Comment by CloCkWeRX** [comment]
Seems about time, @rjaus - thoughts?

**Comment by dwkns** [comment]
Any news on this? @CloCkWeRX @rjaus ? If nothing else to suppress the Big Decimal error.

**Comment by CloCkWeRX** [comment]
Well, I pushed the tag; but don't have publish rights to publish the actual gem; sorry folks!

**Comment by michebble** [comment]
Any news on this? @CloCkWeRX @rjaus?

**Comment by CloCkWeRX** [comment]
Sadly, I can't publish rubygems still; but have pushed a 2.20.0 tag.

**Comment by SidneyAllen** [comment]
Hi @CloCkWeRX 

@rjaus is no longer with Xero.   Wayne the creator of Xeroizer had added both Riley and myself as owners so I maybe able to assist publishing this release.

Anything left to do with the 2.20.0?

**Comment by SidneyAllen** [comment]
Both 2.19.0 and 2.20.0 have been released!
