### ISSUE TITLE
Invoice email method returns http 500 error

### ISSUE THREAD

**Issue by alexgeofilter** [waynerobinson/xeroizer#474]
When using the recently merged invoice email method #469 , it returns a 500 error with a valid invoice. 

For ex:

`invoice = client.Invoice.find(invoice_id)`
`invoice.email`

I have dug into the code to verify whether the implementation should work. I was able to put together a valid request url using the params present in the invoice object. It's possible the http_request method does not correctly form the post request for this email method. If someone could verify whether #469 works, that would be great :)

**Comment by CloCkWeRX** [comment]
@stephenbinns

**Comment by stephenbinns** [comment]
Believe this does still work - however there are a number of caveats mentioned on the API documentation. As you're receiving a 500 error are you able to give any additional context?

**Comment by rjaus** [comment]
Would need more context on this issue to resolve.  May have been resolved via the API itself already.

Re-open if still present.
