### ISSUE TITLE
Can't search by line items because of missing permission

### ISSUE THREAD

**Issue by StaverDmitry** [waynerobinson/xeroizer#479]
`xero_app.LineItem.all` won't work because it raises `NoMethodError: undefined method '[]' for nil:NilClass` in `lib/xeroizer/record/base_model.rb:121` when trying to retrieve class permissions.
I noticed `set_permissions` is missing in models/line_item.rb contrary to models/invoice.rb
That's probably the reason for this error.

**Comment by CloCkWeRX** [comment]
https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/line_item.rb#L7 now features this
