### ISSUE TITLE
OAuth::Error might not get wrapped in Xeroizer::OAuth::OAuthError

### ISSUE THREAD

**Issue by fnordfish** [waynerobinson/xeroizer#482]
When using a PartnerApplication and calling `renew_access_token`, errors like `OAuth::Unauthorized` are not wrapped into `Xeroizer::OAuth::OAuthError`-classes.
Those would be very handy to differentiate "token_rejected", "nonce_used", "signature_invalid" etc. errors. Even just grouping them all under a single `Xeroizer::OAuth::UnauthorizedError` would be nice, so that the caller don't need to tap into a different namespace when calling Xeroizer.

**Comment by CloCkWeRX** [comment]
This may actually be partially addressed in #503
```
        case problem
        when "token_expired"                then raise OAuth::TokenExpired.new(description)
        when "token_rejected"               then raise OAuth::TokenInvalid.new(description)
        when "rate limit exceeded"          then raise OAuth::RateLimitExceeded.new(description)
        when "consumer_key_unknown"         then raise OAuth::ConsumerKeyUnknown.new(description)
        when "nonce_used"                   then raise OAuth::NonceUsed.new(description)
        when "organisation offline"         then raise OAuth::OrganisationOffline.new(description)
        else raise OAuth::UnknownError.new(problem + ':' + description)
```
