### ISSUE TITLE
Client `expires_at` is `nil` when `#authorize_from_access` is used

### ISSUE THREAD

**Issue by pond** [waynerobinson/xeroizer#490]
In a Partner Application client instance initialised with an access token via `#authorize_from_access` rather than `#authorize_from_request`, the client's `expires_at` and `authorization_expires_at` values return `nil`. This is quite destructive since Xeroizer has no automated renewal and raises exceptions for expired tokens, making control flow in any non-trivial application very difficult. One cannot proactively defend against unexpected expiry exceptions via renewal based on token expiry date.

We've had to kludge around this by storing expiry data in our settings store but that's messy. Either the `expires_at`/`authorization_expires_at` accessors should work in all cases, or they should be removed.

**Comment by CloCkWeRX** [comment]
Do you want to see if this is still an issue with the revised oauth2 work merged into master from #500 and #503 ?

I haven't poked around under the hood to see if it's Xero API side or Xeroizer side.

**Comment by mcfiredrill** [comment]
I'm also seeing null for `expire_at` when using `renew_access_token`.

**Comment by pond** [comment]
@CloCkWeRX Thanks for the reply & suggestion.

It may take us quite some time to get around to OAuth 2. Integrating with the Xero OAuth 1 system was very difficult due to all of its many quirks. It took disproportionate effort compared to every other integration we've done, which luckily were standard OAuth 2 with no bespoke quirks. Since it now works and since we're a small startup, we don't have the financial resources to commit to reworking that system in order to chase an API change.

Inevitably change will be forced upon us eventually, once OAuth 1 gets shut down, so we _do_ intend to migrate at our earliest opportunity - but this opportunity might be a while away yet! I'll do my best to remember to come back here and update the issue once we're there.

**Comment by pond** [comment]
@CloCkWeRX Thanks for the reply & suggestion.

I didn't notice the OAuth 2 work until you mentioned it. The PRs appear to contain a huge amount of work; this does make me a bit nervous about early adoption. I see no references at all to any of this in the top level `README.md` though - has the gem itself remained entirely 100% API compatible with its clients but now talks OAuth 2 "under the hood", or are there as-yet-undocumented things one must do in order to invoke OAuth 2 support?

**Comment by rjaus** [comment]
v3 of wrapper deprecates OAuth1.  In alignment with XeroAPI deprecated OAuth1.

See PR: https://github.com/waynerobinson/xeroizer/pull/542
