### ISSUE TITLE
Question: Does Xeroizer support OAuth 2?

### ISSUE THREAD

**Issue by lesliev** [waynerobinson/xeroizer#515]
Does Xeroizer support OAuth 2? 
Xero recommends moving all apps to OAuth 2 well before OAuth 1 is deprecated in March 2021.

**Comment by lesliev** [comment]
I see it does seem to support it: https://github.com/waynerobinson/xeroizer/pull/500

**Comment by nahzz** [comment]
yeah it supports OAuth2 on master branch.  You need to manage the access_token/refresh_token yourself , though.
