### ISSUE TITLE
`.sent_to_contact` on Invoices is undefined

### ISSUE THREAD

**Issue by LimeBlast** [waynerobinson/xeroizer#516]
I'm sorry if this is the wrong place to post this, but I'm having some trouble with an inherited app that uses Xeroizer, so I'd appreciate some guidance.

Long story short, the app makes references to a `sent_to_contact` property on invoices pulled down by the system, and according to the [API documentation for Xero](https://developer.xero.com/documentation/api/invoices#get), a `SentToContact` property exists - but any attempts to use it fail:

```
undefined method 'sent_to_contact' for #<Xeroizer::Record::Invoice:0x000056150c83a1b8>
```

The strange thing is, this seems to work on previous versions of Rails - Rails 3 worked fine, but after upgrading to Rails 5.2, it no longer does.

I'm running  the very latest version of Xeroizer, directly from the github repo (listed as `3.0.0.pre.beta` in the .lock file).

**Comment by petertmiller** [comment]
@LimeBlast This caused me a problem too. It stems from this commit https://github.com/waynerobinson/xeroizer/commit/a4a82dcf20af623f7d19809c9c703e349caeab26 by @francois 

Maybe it got into the master branch by mistake? My solution has been to revert the commit in my repo.

**Comment by francois** [comment]
Yikes, really sorry. That was supposed to stay on our fork.

**Comment by LimeBlast** [comment]
Thanks folks :)
