### ISSUE TITLE
Update the readme/documentation to include Oauth2Application

### ISSUE THREAD

**Issue by christiaanenel** [waynerobinson/xeroizer#525]
Hi there, Any Idea when the readme will be updated to include an example of an Oauth2 App?  Having trouble setting this up on my end. I'm trying to migrate to oauth2 before the end of December :thinking:

**Comment by lopesrb** [comment]
pherhaps @AndyWendt can help. 
I believe he is the one that made all the major modifications

the PR is here https://github.com/waynerobinson/xeroizer/pull/500

**Comment by CloCkWeRX** [comment]
Feel free to have an explore and submit your results as a PR
