### ISSUE TITLE
Xero Deprecation Notice - OAuth 1.0a

### ISSUE THREAD

**Issue by jph** [waynerobinson/xeroizer#526]
Hello,

I have not seen an issue referring to this notice. Xero has deprecated the OAuth 1.0a authentication strategy and are disabling it completely in March 2021.

More info at Xero: https://developer.xero.com/documentation/oauth2/overview
Section: Migrating from OAuth 1.0a

Timeline (from above link)

- Early December 2019 - No new OAuth 1.0a apps created.
- Mid December 2019 - OAuth 2.0 migration endpoint available to partner apps.
- December 2020 - All certified partner apps required to be on OAuth 2.0.
- March 2021 - OAuth 1.0a will no longer be supported for any apps.

Does this gem support the OAuth 2.0 authentication strategy? I have several apps where Xeroizer's implemented and it looks like I will have to perform a migration soon.

Thank you.

e: Have found an issue relating to OAuth 2.0: #525

**Comment by CloCkWeRX** [comment]
#525
