### ISSUE TITLE
Timeout option not set correctly on OAuth 2 client

### ISSUE THREAD

**Issue by artspool-nyc** [waynerobinson/xeroizer#527]
It seems that the OAuth 2 client uses a `connection_opts` hash to set the timeout options, and this is currently empty even when initializing `Xeroizer::OAuth2Application` with a timeout option per issue #296. The options I'm seeing on the `OAuth2::Client` when making a request are:

```
 :authorize_url => "https://login.xero.com/identity/connect/authorize"
 :token_url => "https://identity.xero.com/connect/token"
 :token_method => :post
 :auth_scheme => :request_body
 :connection_opts => Empty Hash
 :connection_build => nil
 :max_redirects => 5
 :raise_errors => false
 :xero_url => "https://api.xero.com/api.xro/2.0"
 :tenets_url => "https://api.xero.com/connections"
 :unitdp => 4
 :timeout => 20
 :access_token => "the-access-token"
 :tenant_id => "the-tenant-id"
```

Is there a different way we should be initializing the `Xeroizer::OAuth2Application` to pass in the timeout options? See [Slow OAuth Providers](https://github.com/oauth-xx/oauth2/wiki/Advanced-usage#slow-oauth-providers) in the oauth2 docs for more info.

**Comment by xxswingxx** [comment]
I started noticing Faraday::TimeoutError: Net::ReadTimeout exceptions due to this I think.

**Comment by xxswingxx** [comment]
@artspool-nyc I think you can pass `connection_opts: { request: { timeout: 300 } }` directly through the `Xeroizer::OAuth2Application` options: 

```ruby
Xeroizer::OAuth2Application.new(client_id, client_secret, 
  connection_opts: { request: { timeout: 300 } },
  rate_limit_sleep: 2,
  unitdp: 4,
  tenant_id: tenant_id
)
```

For what I'm seeing this options are passed directly from the `Xeroizer::OAuth2Application` initializer (https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/oauth2_application.rb#L32) to the  `Xeroizer::OAuth2` initializer (https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/oauth2.rb#L9) and from there to the regular `OAuth2::Client`

**Comment by rjaus** [comment]
Documented: https://github.com/waynerobinson/xeroizer/wiki/OAuth-Client-Connection-Options---Timeouts

Not an issue to fix, closing.
