### ISSUE TITLE
NameError: uninitialized constant Xeroizer::OAuth2Application

### ISSUE THREAD

**Issue by phpdeveloper07** [waynerobinson/xeroizer#544]
Getting uninitialized error, event after declaring it in initializers.

here is the current declaration. Don't know what to update. 

$xero = Xeroizer::OAuth2Application.new(ENV['XERO_OAUTH_CONSUMER_KEY'], ENV['XERO_OAUTH_CONSUMER_SECRET'])

Am I need to add or update anything?

**Comment by rjaus** [comment]
Hey @phpdeveloper07, this doesn't sound like an issue with the SDK.

Can you add your initalizer and the code where you're using the Xeroizer gem?

**Comment by phpdeveloper07** [comment]
Already does that. but still no luck. 

I'm using the docker image ruby:2.3.1-onbuild. (https://hub.docker.com/layers/ruby/library/ruby/2.3.1-onbuild/images/sha256-1ea4979ce53fad605f1ac150d4ee7a5c5ca38e4993b9e2558d5a8157bf85b7c4?context=explore) 

Am I need to do something extra with this Image or any issue with Gemfile. lock?

**Comment by rjaus** [comment]
Sorry I meant post you code here, so we can evaluate.

Looks like the docker image copys the Gemfile and then runs bundle install.

Do you have the xeroizer gem in your Gemfile?

I'd suggest connecting to the running container and checking that your Gems are installed correctly.  If your code runs locally, but not in the docker image then it sounds like the docker image setup is the issue.

**Comment by rjaus** [comment]
I'm going to close this, but if you're still facing the issue feel free to re-open with more info.

Cheers!
