### ISSUE TITLE
Double raise for expired tokens? 

### ISSUE THREAD

**Issue by kitebuggy** [waynerobinson/xeroizer#545]
Hi all,

I'm struggling to understand why an Expired Token 401 message would trigger two errors being raised, one immediately after the other: 

https://github.com/waynerobinson/xeroizer/blob/b78a9a0b1933649b74cb3877c56b6b702ac0cc33/lib/xeroizer/http_response.rb#L135

Shouldn't this really be an if .. then ... else ... selection of these two errors?  @AndyWendt and @jhiggi44 - do you recall why it was done this way?

I'm happy to submit a PR, but before I did so, I wanted to double-check that this odd behaviour wasn't actually intentional?

Thanks,

Jason

**Comment by rjaus** [comment]
Good time to throw in a PR, as a release will be going out early next week. (was aiming for today, but Friday release is probably a baaaaaad idea :)

**Comment by kitebuggy** [comment]
Submitted PR to address (please excuse the tweaks to .gitignore for us old-school emacs users!)
