### ISSUE TITLE
syntax error, unexpected ',' in branding_theme.rb 

### ISSUE THREAD

**Issue by joseramos19** [waynerobinson/xeroizer#552]
Just upgraded to Xero 3.0.1 and got this error upon running a rake command. The syntax is fine, its just weird that it doesn't parse the "keyword arguments" properly. Im using Ruby 2.0.0.

![image](https://user-images.githubusercontent.com/43330523/140462553-2a401909-4109-4697-8c36-8e4d733056b2.png)

**Comment by CloCkWeRX** [comment]
Ruby 2.0.0 is... Very old. I would strongly recommend upgrading if you have not done so already. Happy to put in min versions to the gemspec if others experience the same issue
