### ISSUE TITLE
How do you run the tests for Xeroizer?

### ISSUE THREAD

**Issue by corroded** [waynerobinson/xeroizer#73]
We've been trying to run it but it seems it needs ENV["CONSUMER_KEY"], ENV["CONSUMER_SECRET"], and ENV["KEY_FILE"]

I assume key and secret are our applications api key and secret, but what is the key file? I'm thinking it is for partner/private apps, but what if your app is pubic? Why is it required?

**Comment by rjaus** [comment]
Added documentation on how to run the test to the README: https://github.com/waynerobinson/xeroizer#tests
