### ISSUE TITLE
Ability to create expenses

### ISSUE THREAD

**Issue by patrickberkeley** [waynerobinson/xeroizer#77]
I'd like the ability to create expenses. Is this a planned feature?

**Comment by rjaus** [comment]
Expense claims & receipts are both supported now:
https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/expense_claim.rb

https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/receipt.rb
