### ISSUE TITLE
Reading privatekey from environment variable

### ISSUE THREAD

**Issue by ghost** [waynerobinson/xeroizer#80]
Our application runs on heroku and I didn't want to commit the private key to git. 
I am documenting here what I did to provide a private key from an environment variable. 
1. Set the config variable in the heroku environment, e.g.
   `heroku config:set PRIVATEKEY=$( cat private_key_file ) --app app_name` 
2. In RoR 
   `@client = Xeroizer::PrivateApplication.new(
               OAUTH_CONSUMER_KEY,
               OAUTH_CONSUMER_SECRET,
               '| echo "$PRIVATEKEY" ' )`

Note: it is important to enclose the $PRIVATEKEY in double quotes to preserve the newlines in the PRIVATEKEY variable value.

This works well since in the oauth gem the "privatekeyfile" is opened with an IO.read(<..>) which can read from a subprocess echo in this instance.

**Comment by lneffa** [comment]
Thanks!
