### ISSUE TITLE
Totals missing in BankTransactions

### ISSUE THREAD

**Issue by jtakhar** [waynerobinson/xeroizer#91]
Hi - im trying to get the SPEND BankTransactions. I can get the BankTransactions but i the totals are not present. I think a change was made in Xero's  API which may have broken your code.

This is an example BankTransaction (from the Demo account) im seeing from your gem. As you can see Total/SubTotal etc are all missing.
# <Xeroizer::Record::BankTransaction :line_amount_types: "Inclusive", :contact: #<Xeroizer::Record::Contact :contact_id: "b89da77c-1a13-4893-8d65-71cd38fc623a", :name: "Fulton Airport Parking">, :date: Mon, 08 Jul 2013, :updated_date_utc: Mon, 08 Jul 2013, :bank_transaction_id: "8d9e73dd-2a51-4f2d-bd52-84bd56eb079b", :bank_account: #<Xeroizer::Record::BankAccount :account_id: "15cb3742-e516-451a-9468-2b362fd2b017">, :type: "SPEND", :is_reconciled: true>

**Comment by CloCkWeRX** [comment]
As you can see in https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/bank_transaction.rb#L67 ; total/subtotal/etc are methods not attributes.
