### ISSUE TITLE
Why do we need to download a record before updating it?

### ISSUE THREAD

**Issue by corroded** [waynerobinson/xeroizer#99]
from docs:

"If the primary GUID for the record is present, the library will attempt to update the record instead of creating it. It is important that this record is downloaded from the Xero API first before attempting an update. For example:"

```
contact = xero.Contact.find("cd09aa49-134d-40fb-a52b-b63c6a91d712")
contact.name = "Another Name Change"
contact.save
```

I am asking because our app supports 2-way syncing: either you put changes from Xero to the app or vice versa. Syncing is done as a job as a whole, so to save on API calls, we use the batch_save feature (by @fimmtiu). Problem with this is if there are 100+ records, you need to select them all by bulk. Otherwise you'll have to have a separate API call to download each of the records from Xero before updating them. 

Based on the API though, it looks like Xero just accepts the id, no need to download the records. Is there an architectural issue why we need to download first? Thanks!

**Comment by brancusi** [comment]
Hi,

I'm actually running into issues around this. We are just about to hit our rate limit. We are using one way data flow, for the most part, and just overriding any lapsed changes in xero. An option to post changes without first loading the record would help.

Reading the xero docs, it sounds like included fields are merged and a completely new record is not created in xero.

Any ideas?

Thanks

**Comment by waynerobinson** [comment]
I'm not sure about currently, but originally the days was not merged with
the existing on update and any missing fields were set to null in Xero.

If you can verify this has changed I'm happy to receive a PR.

**Comment by brancusi** [comment]
Hi @waynerobinson, this is the snippet from the docs

```xml

<Contact>
  <ContactID>eaa28f49-6028-4b6e-bb12-d8f6278073fc</ContactID>
  <ContactNumber>ID001</ContactNumber>
  <Name>ABC Limited</Name>
  <FirstName>John</FirstName>
  <LastName>Smith</LastName>
  <EmailAddress>john.smith@gmail.com</EmailAddress>
  <Addresses>  
    <Address>  
      <AddressType>POBOX</AddressType>  
        <AddressLine1>P O Box 123</AddressLine1>  
        <City>Wellington</City>  
        <PostalCode>6011</PostalCode> 
      </Address>
  </Addresses> 
  <BankAccountDetails>01-0123-0123456-00</BankAccountDetails>
  <TaxNumber>12-345-678</TaxNumber>
  <AccountsReceivableTaxType>OUTPUT</AccountsReceivableTaxType>
  <AccountsPayableTaxType>INPUT</AccountsPayableTaxType>
  <DefaultCurrency>NZD</DefaultCurrency>
</Contact>
```

> When you are updating a contact you don’t need to specify every element. If you exclude an element then the existing value of that field will be preserved. For example in the example above the existing phone numbers will be preserved as they were not specified.

> If you are updating contacts to match those of another system we recommend that you try and update as many fields as possible.

What do you think? Is this what they always said and it just doesn't actually work this way?

For us, we are storing the contact_id as the foreign_key to xero. This is our way of seeing if the record has been persisted to xero at which point there is no for us to pull the record first.

Lastly, on another note, does xero force using PUT when creating records? Seems like if POST was used by default during batch save, we could have more flexibility in creating or updating in the batch create/update without xeroizer needing to determine if it should be a save or update. We could just mix both new records and update records in the same post right? Or am I missing something here.

Thank you
